import test from 'node:test';
import assert from 'node:assert/strict';
import { authenticateFrontier, createFrontierRoom, frontierAct, frontierView, joinFrontierRoom } from '../server/frontier-engine.mjs';
import { FRONTIER_REGION_BY_ID } from '../lib/frontier-map.mjs';

function setup(count=3){const room=createFrontierRoom('Joueur 1');for(let i=2;i<=count;i++)joinFrontierRoom(room,`Joueur ${i}`);for(const player of room.players)frontierAct(room,player,'ready');frontierAct(room,room.players[0],'start');return room}

test('creates a 2-6 player campaign with private tokens and balanced starts',()=>{for(let count=2;count<=6;count++){const room=setup(count),view=frontierView(room,room.players[0]);assert.equal(room.players.length,count);assert.equal(Object.values(room.game.owners).filter(Boolean).length,count*2);assert.ok(room.players.every(player=>Object.values(room.game.owners).filter(owner=>owner===player.id).length===2));assert.ok(view.players.every(player=>!('token'in player)));assert.throws(()=>authenticateFrontier(room,'bad-token'))}});

test('orders remain private until every player locks and then advance the round',()=>{const room=setup(2),[alice,bob]=room.players;const source=Object.keys(room.game.owners).find(region=>room.game.owners[region]===alice.id&&FRONTIER_REGION_BY_ID[region].links.some(link=>room.game.owners[link]!==alice.id));const target=FRONTIER_REGION_BY_ID[source].links.find(link=>room.game.owners[link]!==alice.id);frontierAct(room,alice,'move',{round:1,from:source,to:target,amount:1});assert.equal(frontierView(room,alice).game.myOrders.length,1);assert.equal(frontierView(room,bob).game.myOrders.length,0);assert.equal(frontierView(room,bob).game.orderCounts[alice.id],1);frontierAct(room,alice,'lock',{round:1});frontierAct(room,bob,'lock',{round:1});assert.equal(room.game.round,2);assert.equal(room.game.locked.length,0);assert.ok(room.game.log.length>1)});

test('recruitment spends supply and domination ends the game',()=>{const room=setup(2),player=room.players[0],region=Object.keys(room.game.owners).find(id=>room.game.owners[id]===player.id),before=room.game.armies[region];frontierAct(room,player,'recruit',{round:1,region,amount:2});frontierAct(room,player,'lock',{round:1});frontierAct(room,room.players[1],'lock',{round:1});assert.equal(room.game.armies[region],before+2);assert.ok(room.game.supply[player.id]>=0);for(const id of Object.keys(room.game.owners).slice(0,7))room.game.owners[id]=player.id;room.game.round=2;frontierAct(room,player,'lock',{round:2});frontierAct(room,room.players[1],'lock',{round:2});assert.equal(room.game.phase,'finished');assert.equal(room.game.winner,player.id)});

test('rejects impossible moves, excess orders and leaving mid-campaign',()=>{const room=setup(2),player=room.players[0],owned=Object.keys(room.game.owners).filter(id=>room.game.owners[id]===player.id);const remote=Object.keys(room.game.owners).find(id=>!FRONTIER_REGION_BY_ID[owned[0]].links.includes(id)&&id!==owned[0]);assert.throws(()=>frontierAct(room,player,'move',{round:1,from:owned[0],to:remote,amount:1}));assert.throws(()=>frontierAct(room,player,'leave'));frontierAct(room,player,'recruit',{round:1,region:owned[0],amount:1});frontierAct(room,player,'recruit',{round:1,region:owned[0],amount:1});assert.throws(()=>frontierAct(room,player,'recruit',{round:1,region:owned[0],amount:1}))});
