import test from 'node:test';import assert from 'node:assert/strict';
import { authenticateMetro,createMetroRoom,joinMetroRoom,metroAct,metroView } from '../server/metro-engine.mjs';
function roomWith(n=2){const room=createMetroRoom('Alice');for(let i=1;i<n;i++)joinMetroRoom(room,`Joueur ${i+1}`);for(const p of room.players)metroAct(room,p,'ready');metroAct(room,room.players[0],'start');return room}
function act(room,p,action,data={}){metroAct(room,p,action,{revision:room.game.round*100+room.game.turn,...data})}
function current(room){return room.players.find(p=>p.id===room.game.current)}
test('creates private rooms for two to six players',()=>{const room=roomWith(6);assert.equal(room.players.length,6);assert.throws(()=>joinMetroRoom(room,'Trop tard'));const view=metroView(room,room.players[0]);assert.ok(view.players.every(p=>!('token'in p)));assert.throws(()=>authenticateMetro(room,'bad'))});
test('every player starts on the upper-left salary and dice moves the active token',()=>{const room=roomWith();const p=current(room);assert.equal(room.game.phase,'roll');assert.ok(Object.values(room.game.positions).every(pos=>pos.route==='ouest-direct'&&pos.index===2));act(room,p,'roll');const pos=room.game.positions[p.id];assert.ok(pos.station||pos.route);assert.ok(room.game.lastLanding||room.game.lastEvent)});
test('choosing a direction at a station prepares the selected route',()=>{const room=roomWith();const p=current(room);room.game.positions[p.id]={station:'central'};room.game.phase='route';act(room,p,'choose-route',{route:'central-direct'});assert.equal(room.game.phase,'roll');assert.deepEqual(room.game.positions[p.id],{route:'central-direct',index:-1})});
test('buying and selling property updates cash and ownership',()=>{const room=roomWith();const p=current(room);room.game.phase='purchase';room.game.pending={node:'l5',price:160};act(room,p,'buy');assert.equal(room.game.owners.l5,p.id);assert.equal(room.game.money[p.id],1340);room.game.current=p.id;room.game.phase='debt';room.game.money[p.id]=-50;room.game.pending={creditor:null};act(room,p,'sell',{node:'l5'});assert.equal(room.game.owners.l5,undefined);assert.equal(room.game.money[p.id],30)});
test('bankruptcy removes holdings and can end the game',()=>{const room=roomWith();const p=current(room);room.game.owners.cd2=p.id;room.game.phase='debt';room.game.money[p.id]=-100;act(room,p,'bankrupt');assert.ok(room.game.bankrupt.includes(p.id));assert.equal(room.game.owners.cd2,undefined);assert.equal(room.game.phase,'finished');assert.notEqual(room.game.winner,p.id)});
test('twentieth day awards victory to highest net worth',()=>{const room=roomWith(3);const p=current(room);room.game.round=21;room.game.phase='purchase';room.game.pending={node:'cd2',price:160};act(room,p,'skip');assert.equal(room.game.phase,'finished');assert.ok(room.game.winner);assert.match(room.game.reason,/patrimoine/)});
test('rejects invalid routes, stale turns and rooms from another game',()=>{const room=roomWith();const p=current(room);assert.throws(()=>act(room,p,'choose-route',{route:'est-riviera'}));assert.throws(()=>metroAct(room,p,'choose-route',{revision:999,route:'central-direct'}));assert.throws(()=>joinMetroRoom({...room,kind:'shadows'},'Intrus'))});
