import test from 'node:test';import assert from 'node:assert/strict';
import {createMetroRoom,joinMetroRoom,metroAct,metroView} from '../server/metro-engine.mjs';
import {createMarket,settleMarketDay,marketShock,portfolioValue,stockTransaction} from '../server/metro-market.mjs';
import {UNIQUE_NODES,ROUTES} from '../lib/metro-board.mjs';
function setup(map='classic'){const r=createMetroRoom('Alice');joinMetroRoom(r,'Bob');metroAct(r,r.players[0],'configure',{map,startingCash:3000});r.players.forEach(p=>metroAct(r,p,'ready'));metroAct(r,r.players[0],'start');return r;}
function player(r){return r.players.find(p=>p.id===r.game.current);}
function act(r,action,data={},p=player(r)){metroAct(r,p,action,{revision:r.game.round*100+r.game.turn,marketRevision:r.game.market?.revision,...data});}
test('new games list only the companies on the selected board',()=>{assert.equal(Object.keys(setup().game.market.stocks).length,2);assert.equal(Object.keys(setup('network').game.market.stocks).length,6);});
test('purchase books fees, holdings, cost basis, limited float and public wealth',()=>{const r=setup(),p=player(r),stock=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:stock.id,quantity:10});assert.equal(r.game.money[p.id],2592);assert.equal(stock.holdings[p.id],10);assert.equal(stock.costBasis[p.id],408);assert.equal(stock.available,90);assert.equal(r.game.stockActions,1);const view=metroView(r,p);assert.equal(view.game.stockWorth[p.id],10*stock.price);assert.equal(view.game.worth[p.id],2592+10*stock.price);});
test('sale releases shares, allocates cost basis and records realized gain',()=>{const r=setup(),p=player(r),s=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:s.id,quantity:10});marketShock(r.game.market,10,'Croissance');const price=s.price;act(r,'sell-stock',{node:s.id,quantity:5});assert.equal(s.holdings[p.id],5);assert.equal(s.available,95);assert.equal(s.costBasis[p.id],204);assert.equal(s.realized[p.id],5*price-Math.ceil(5*price*.02)-204);});
test('rejects invalid quantities, stale quotes, other players and unavailable funds or shares',()=>{const r=setup(),p=player(r),s=r.game.market.stocks['classic-12'];for(const quantity of [0,-1,1.5,'2',Infinity,101])assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity}));assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity:1,marketRevision:-1}));assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity:1},r.players.find(x=>x.id!==p.id)));assert.throws(()=>act(r,'sell-stock',{node:s.id,quantity:1}));assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity:100}));s.available=0;assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity:1}));assert.equal(r.game.money[p.id],3000);});
test('unlimited operations within funds and no stock trading during auctions',()=>{const r=setup(),s=r.game.market.stocks['classic-12'];for(let i=0;i<5;i++)act(r,'buy-stock',{node:s.id,quantity:1});assert.equal(s.holdings[player(r).id],5);r.game.stockActions=0;r.game.phase='auction';assert.throws(()=>act(r,'buy-stock',{node:s.id,quantity:1}));});
test('players can liquidate shares to pay debt despite turn limit',()=>{const r=setup(),p=player(r),s=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:s.id,quantity:10});r.game.stockActions=3;r.game.phase='debt';r.game.pending={creditor:null};r.game.money[p.id]=-100;act(r,'sell-stock',{node:s.id,quantity:5});assert.ok(r.game.money[p.id]>=0);assert.notEqual(r.game.phase,'debt');assert.equal(s.holdings[p.id],5);});
test('daily market fluctuations, dividends, quote bounds and capped history',()=>{const m=createMarket(UNIQUE_NODES),s=m.stocks.l1;const money={a:0};s.holdings.a=3;s.available-=3;settleMarketDay(m,money,[],2,()=>3);assert.equal(m.day,2);assert.equal(money.a,3);assert.ok(s.price>s.opening);for(let i=0;i<30;i++)marketShock(m,100,'Hausse');assert.ok(Object.values(m.stocks).every(s=>s.price<=500&&s.history.length<=24));marketShock(m,-100,'Chute');assert.equal(s.price,5);assert.ok(m.news.length<=8);});
test('construction changes energy and utility prices and events support sector shocks',()=>{const r=setup(),p=player(r);r.game.owners['classic-1']=p.id;r.game.owners['classic-3']=p.id;const s=r.game.market.stocks['classic-12'],before=s.price;act(r,'build',{node:'classic-1'});assert.ok(s.price>before);assert.match(s.reason,/Construction/);const m=createMarket(UNIQUE_NODES),industrial=m.stocks.l1,water=m.stocks.h15;const old=industrial.price;marketShock(m,10,'Travaux',['Réseaux']);assert.equal(industrial.price,old);assert.ok(water.price>32);});
test('company landing opens investment instead of property purchase; closing advances turn',()=>{const r=setup('network'),p=player(r),route=ROUTES['central-nord'],original=route.nodes;route.nodes=Array(20).fill(UNIQUE_NODES.find(n=>n.id==='l1'));try{r.game.positions[p.id]={route:'central-nord',index:0};act(r,'roll');assert.equal(r.game.phase,'investment');assert.equal(r.game.pending.node,'l1');r.game.extraTurn=false;act(r,'close-market');assert.notEqual(r.game.current,p.id);}finally{route.nodes=original;}});
test('daily settlement happens once on round change, never after a double',()=>{const r=setup();const g=r.game;g.current=g.order.at(-1);g.extraTurn=false;g.phase='purchase';g.pending={node:'classic-1',price:60};r.settings.auction=false;act(r,'skip');assert.equal(g.round,2);assert.equal(g.market.day,2);const rev=g.market.revision;g.phase='purchase';g.pending={node:'classic-3',price:60};g.extraTurn=true;act(r,'skip');assert.equal(g.market.revision,rev);});
test('own demand cannot generate profit through an immediate round trip',()=>{for(const price of [5,17,25,26,40,60,100,499])for(const q of [1,10,50,100]){const m=createMarket(UNIQUE_NODES),s=m.stocks.l1;s.price=price;const money={a:100000};stockTransaction(m,'a',s.id,q,false,money);stockTransaction(m,'a',s.id,q,true,money);assert.ok(money.a<=100000,price+' / '+q);}});
test('bankruptcy returns stock float and removes portfolio value',()=>{const r=setup(),p=player(r),s=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:s.id,quantity:10});r.game.phase='debt';r.game.money[p.id]=-100;act(r,'bankrupt');assert.equal(s.available,100);assert.equal(portfolioValue(r.game.market,p.id),0);});
test('old rooms keep company ownership without a stock market',()=>{const r=setup();delete r.game.market;assert.equal(metroView(r,player(r)).game.market,null);assert.throws(()=>act(r,'buy-stock',{node:'classic-12',quantity:1}));});

test('stock trades transfer shares and cost basis without changing float or cash',()=>{const r=setup(),a=player(r),b=r.players.find(p=>p.id!==a.id),s=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:s.id,quantity:10});const basis=s.costBasis[a.id],available=s.available;act(r,'propose-trade',{to:b.id,offerStocks:{[s.id]:4}});act(r,'accept-trade',{offerId:r.game.tradeOffers[0].id},b);assert.equal(s.holdings[a.id],6);assert.equal(s.holdings[b.id],4);assert.ok(Math.abs(s.costBasis[b.id]-basis*.4)<1e-9);assert.equal(s.available,available);});
test('stock offer acceptance rejects sold shares without partial property transfer',()=>{const r=setup(),a=player(r),b=r.players.find(p=>p.id!==a.id),s=r.game.market.stocks['classic-12'];act(r,'buy-stock',{node:s.id,quantity:3});r.game.owners['classic-1']=a.id;act(r,'propose-trade',{to:b.id,offerNodes:['classic-1'],offerStocks:{[s.id]:3}});act(r,'sell-stock',{node:s.id,quantity:2});assert.throws(()=>act(r,'accept-trade',{offerId:r.game.tradeOffers[0].id},b));assert.equal(r.game.owners['classic-1'],a.id);});

test('movement follows every classic tile and records the station on network routes',()=>{const r=setup(),p=player(r);act(r,'roll');assert.equal(r.game.movement.player,p.id);assert.equal(r.game.movement.path.length,r.game.lastRoll.total);assert.equal(r.game.movement.path.at(-1),r.game.lastLanding);const n=setup('network'),q=player(n);n.game.positions[q.id]={route:'central-nord',index:ROUTES['central-nord'].nodes.length-1};n.game.phase='roll';act(n,'roll');assert.deepEqual(n.game.movement.path,[ROUTES['central-nord'].to]);});
