import test from 'node:test';import assert from 'node:assert/strict';
import { authenticateMetro,createMetroRoom,joinMetroRoom,metroAct,metroView } from '../server/metro-engine.mjs';
function roomWith(n=2){const room=createMetroRoom('Alice');for(let i=1;i<n;i++)joinMetroRoom(room,`Joueur ${i+1}`);for(const p of room.players)metroAct(room,p,'ready');metroAct(room,room.players[0],'start');return room}
function act(room,p,action,data={}){metroAct(room,p,action,{revision:room.game.round*100+room.game.turn,...data})}
function current(room){return room.players.find(p=>p.id===room.game.current)}
test('creates private rooms for two to six players',()=>{const room=roomWith(6);assert.equal(room.players.length,6);assert.throws(()=>joinMetroRoom(room,'Trop tard'));const view=metroView(room,room.players[0]);assert.ok(view.players.every(p=>!('token'in p)));assert.throws(()=>authenticateMetro(room,'bad'))});
test('every player starts on the upper-left salary and dice moves the active token',()=>{const room=roomWith();const p=current(room);assert.equal(room.game.phase,'roll');assert.ok(Object.values(room.game.positions).every(pos=>pos.route==='ouest-direct'&&pos.index===2));act(room,p,'roll');const pos=room.game.positions[p.id];assert.ok(pos.station||pos.route);assert.ok(room.game.lastLanding||room.game.lastEvent)});
test('choosing a direction at a station prepares the selected route',()=>{const room=roomWith();const p=current(room);room.game.positions[p.id]={station:'central'};room.game.phase='route';act(room,p,'choose-route',{route:'central-direct'});assert.equal(room.game.phase,'roll');assert.deepEqual(room.game.positions[p.id],{route:'central-direct',index:-1})});
test('stations can be purchased and add to net worth',()=>{const room=roomWith();const p=current(room);room.game.positions[p.id]={station:'central'};room.game.phase='purchase';room.game.pending={node:'central',price:340};act(room,p,'buy');assert.equal(room.game.owners.central,p.id);assert.equal(room.game.money[p.id],1160);assert.ok(metroView(room,p).game.worth[p.id]>=1500)});
test('two dice are public and remaining movement continues after a station choice',()=>{let crossed=null;for(let i=0;i<80&&!crossed;i++){const room=roomWith();const p=current(room);act(room,p,'roll');assert.equal(room.game.lastRoll.dice.length,2);assert.equal(room.game.lastRoll.total,room.game.lastRoll.dice[0]+room.game.lastRoll.dice[1]);if(room.game.phase==='route'&&room.game.remainingMoves>0)crossed={room,p,remaining:room.game.remainingMoves}}assert.ok(crossed,'un lancer doit traverser la gare');const before=crossed.remaining;act(crossed.room,crossed.p,'choose-route',{route:'central-direct'});assert.equal(crossed.room.game.remainingMoves,0);assert.notDeepEqual(crossed.room.game.positions[crossed.p.id],{route:'central-direct',index:-1});assert.ok(before>0)});
test('a double grants another turn',()=>{let found=false;for(let i=0;i<120&&!found;i++){const room=roomWith();const p=current(room);act(room,p,'roll');if(room.game.lastRoll.isDouble){found=true;if(room.game.phase==='purchase')act(room,p,'skip');assert.ok(room.game.current===p.id||room.game.extraTurn)}}assert.ok(found,'un double doit être observable')});
test('players can trade properties at the business cafe',()=>{const room=roomWith();const [alice,bob]=room.players;room.game.owners.l5=alice.id;room.game.owners.m5=bob.id;metroAct(room,alice,'propose-trade',{revision:room.game.round*100+room.game.turn,to:bob.id,offerNode:'l5',wantNode:'m5'});const offer=room.game.tradeOffers[0];assert.ok(offer);metroAct(room,bob,'accept-trade',{revision:room.game.round*100+room.game.turn,offerId:offer.id});assert.equal(room.game.owners.l5,bob.id);assert.equal(room.game.owners.m5,alice.id)});
test('buying and selling property updates cash and ownership',()=>{const room=roomWith();const p=current(room);room.game.phase='purchase';room.game.pending={node:'l5',price:160};act(room,p,'buy');assert.equal(room.game.owners.l5,p.id);assert.equal(room.game.money[p.id],1340);room.game.current=p.id;room.game.phase='debt';room.game.money[p.id]=-50;room.game.pending={creditor:null};act(room,p,'sell',{node:'l5'});assert.equal(room.game.owners.l5,undefined);assert.equal(room.game.money[p.id],30)});
test('bankruptcy removes holdings and can end the game',()=>{const room=roomWith();const p=current(room);room.game.owners.cd2=p.id;room.game.phase='debt';room.game.money[p.id]=-100;act(room,p,'bankrupt');assert.ok(room.game.bankrupt.includes(p.id));assert.equal(room.game.owners.cd2,undefined);assert.equal(room.game.phase,'finished');assert.notEqual(room.game.winner,p.id)});
test('twentieth day awards victory to highest net worth',()=>{const room=roomWith(3);const p=current(room);room.game.round=21;room.game.phase='purchase';room.game.pending={node:'cd2',price:160};act(room,p,'skip');assert.equal(room.game.phase,'finished');assert.ok(room.game.winner);assert.match(room.game.reason,/patrimoine/)});
test('rejects invalid routes, stale turns and rooms from another game',()=>{const room=roomWith();const p=current(room);assert.throws(()=>act(room,p,'choose-route',{route:'est-riviera'}));assert.throws(()=>metroAct(room,p,'choose-route',{revision:999,route:'central-direct'}));assert.throws(()=>joinMetroRoom({...room,kind:'shadows'},'Intrus'))});
