import test from 'node:test';import assert from 'node:assert/strict';import {createMetroRoom,joinMetroRoom,metroAct} from '../server/metro-engine.mjs';
function setup(){const r=createMetroRoom('Alice');joinMetroRoom(r,'Bob');joinMetroRoom(r,'Claire');r.players.forEach(p=>metroAct(r,p,'ready'));metroAct(r,r.players[0],'start');const [a,b]=r.players;r.game.owners={l5:a.id,m5:a.id,f10:b.id,f11:b.id};return r;}
function act(r,p,action,data={}){metroAct(r,p,action,{revision:r.game.round*100+r.game.turn,...data});}
function offer(r,data={}){const [a,b]=r.players;act(r,a,'propose-trade',{to:b.id,offerNodes:['l5','m5'],wantNodes:['f10'],offerCash:100,wantCash:25,...data});return r.game.tradeOffers.at(-1);}
test('multiple properties and money transfer atomically with houses and mortgages retained',()=>{const r=setup(),[a,b]=r.players;r.game.houses.l5=2;r.game.mortgages.f10=true;const o=offer(r);act(r,b,'accept-trade',{offerId:o.id});assert.equal(r.game.owners.l5,b.id);assert.equal(r.game.owners.m5,b.id);assert.equal(r.game.owners.f10,a.id);assert.equal(r.game.money[a.id],1425);assert.equal(r.game.money[b.id],1575);assert.equal(r.game.houses.l5,2);assert.equal(r.game.mortgages.f10,true);assert.equal(r.game.tradeOffers.length,0);});
test('cash can purchase a property without offering another property',()=>{const r=setup(),[a,b]=r.players;const o=offer(r,{offerNodes:[],wantNodes:['f10'],offerCash:250,wantCash:0});act(r,b,'accept-trade',{offerId:o.id});assert.equal(r.game.owners.f10,a.id);assert.equal(r.game.money[b.id],1750);});
test('stale ownership or insufficient funds never partially transfers a trade',()=>{for(const cause of ['owner','cash']){const r=setup(),[a,b,c]=r.players;const o=offer(r);if(cause==='owner')r.game.owners.m5=c.id;else r.game.money[a.id]=50;const before=JSON.stringify({money:r.game.money,owners:r.game.owners});assert.throws(()=>act(r,b,'accept-trade',{offerId:o.id}));assert.equal(JSON.stringify({money:r.game.money,owners:r.game.owners}),before);}});
test('rejects invalid amounts, duplicate assets, empty offers and strangers',()=>{const r=setup();for(const data of [{offerCash:-1},{offerCash:1.5},{offerCash:'100'},{offerCash:Infinity},{offerNodes:['l5','l5']},{offerNodes:[],wantNodes:[],offerCash:0,wantCash:0},{to:'stranger'}])assert.throws(()=>offer(r,data));});
test('only recipient accepts; either participant can reject',()=>{const r=setup(),[a,b,c]=r.players;let o=offer(r);assert.throws(()=>act(r,c,'accept-trade',{offerId:o.id}));assert.throws(()=>act(r,a,'accept-trade',{offerId:o.id}));act(r,a,'reject-trade',{offerId:o.id});assert.equal(r.game.tradeOffers.length,0);o=offer(r);act(r,b,'reject-trade',{offerId:o.id});assert.equal(r.game.owners.l5,a.id);});
test('accepting invalidates competing property offers and prevents double acceptance',()=>{const r=setup(),[,b]=r.players;const o=offer(r);offer(r);act(r,b,'accept-trade',{offerId:o.id});assert.equal(r.game.tradeOffers.length,0);assert.throws(()=>act(r,b,'accept-trade',{offerId:o.id}));});
test('legacy offers remain acceptable and auctions block money transfers',()=>{const r=setup(),[a,b]=r.players;r.game.tradeOffers.push({id:'old',from:a.id,to:b.id,offerNode:'l5',wantNode:'f10'});act(r,b,'accept-trade',{offerId:'old'});assert.equal(r.game.owners.l5,b.id);r.game.phase='auction';assert.throws(()=>offer(r));});
