import test from 'node:test';
import assert from 'node:assert/strict';
import {createMetroRoom,joinMetroRoom,metroAct,metroView} from '../server/metro-engine.mjs';
import {UNIQUE_NODES} from '../lib/metro-classic-board.mjs';
function setup(){const r=createMetroRoom('Alice');joinMetroRoom(r,'Bob');metroAct(r,r.players[0],'configure',{map:'classic',startingCash:1500});r.players.forEach(p=>metroAct(r,p,'ready'));metroAct(r,r.players[0],'start');return r;}
function act(r,action,data={}){const p=r.players.find(p=>p.id===r.game.current);metroAct(r,p,action,{revision:r.game.round*100+r.game.turn,...data});return p;}
test('classic perimeter has forty unique positions and the standard asset distribution',()=>{assert.equal(UNIQUE_NODES.length,40);assert.equal(new Set(UNIQUE_NODES.map(n=>n.x+','+n.y)).size,40);assert.equal(UNIQUE_NODES.filter(n=>n.type==='property').length,22);assert.equal(UNIQUE_NODES.filter(n=>n.type==='station').length,4);assert.equal(UNIQUE_NODES.filter(n=>n.type==='company').length,2);});
test('map choice is host-only, validated, and resets readiness',()=>{const r=createMetroRoom('Alice');const b=joinMetroRoom(r,'Bob');metroAct(r,b,'ready');assert.throws(()=>metroAct(r,b,'configure',{map:'classic',startingCash:1500}));assert.throws(()=>metroAct(r,r.players[0],'configure',{map:'bad',startingCash:1500}));metroAct(r,r.players[0],'configure',{map:'classic',startingCash:1500});assert.ok(r.players.every(p=>!p.ready));});
test('classic players start together and keep moving past the end of the circuit',()=>{const r=setup();for(const p of r.players)assert.deepEqual(r.game.positions[p.id],{route:'classic-loop',index:0});const id=r.game.current;r.game.positions[id].index=39;act(r,'roll');assert.equal(r.game.positions[id].index,r.game.lastRoll.total-1);assert.notEqual(r.game.phase,'route');assert.ok(r.game.money[id]>=1500);assert.equal(metroView(r,r.players[0]).settings.map,'classic');});
test('classic station purchase uses its own price and contributes to public wealth',()=>{const r=setup();r.game.phase='purchase';r.game.pending={node:'classic-5',price:200};const p=act(r,'buy');assert.equal(r.game.owners['classic-5'],p.id);assert.equal(r.game.money[p.id],1300);assert.equal(metroView(r,p).game.worth[p.id],1500);});
test('map cannot be changed after the game starts',()=>{const r=setup();assert.throws(()=>metroAct(r,r.players[0],'configure',{map:'network',startingCash:1500}));});
