import test from 'node:test';import assert from 'node:assert/strict';
import{createTraitorRoom,joinTraitorRoom,traitorAct,traitorView}from'../server/traitor-engine.mjs';
function roomWith(n=3){const room=createTraitorRoom('Alice');for(let i=1;i<n;i++)joinTraitorRoom(room,`Joueur ${i+1}`);for(const p of room.players)traitorAct(room,p,'ready');traitorAct(room,room.players[0],'start');return room}
const act=(room,p,action,data={})=>traitorAct(room,p,action,{turn:room.game.turn,...data});
function setTurn(room,p){room.game.turnIndex=room.players.indexOf(p)}
test('uses official 3-8 player role counts, targets and three-card hands',()=>{for(const [n,mutins,target] of [[3,1,5],[4,1,8],[5,1,11],[6,2,6],[7,2,9],[8,2,12]]){const room=roomWith(n);assert.equal(Object.values(room.game.roles).filter(x=>x==='mutin').length,mutins);assert.equal(room.game.target,target);assert.ok(room.players.every(p=>room.game.hands[p.id].length===3))}});
test('keeps roles, hands and chest values secret',()=>{const room=roomWith(4),pirate=room.players.find(p=>room.game.roles[p.id]==='pirate'),other=room.players.find(p=>p.id!==pirate.id),view=traitorView(room,pirate);assert.equal(view.game.hand.length,3);assert.equal(view.game.revealedRoles,null);assert.equal(view.game.revealedChest,null);assert.equal(view.game.handCounts[other.id],3)});
test('loot can be announced as a bluff and the player draws back to three',()=>{const room=roomWith(),p=room.players[room.game.turnIndex];room.game.hands[p.id]=[{id:'loot',type:'loot',value:-2},{id:'spare',type:'loot',value:1},{id:'spare2',type:'loot',value:0}];act(room,p,'playLoot',{cardId:'loot',announced:1});assert.equal(room.game.chest[0].value,-2);assert.match(room.game.log[0],/\+1/);assert.equal(room.game.hands[p.id].length,3)});
test('three Planche cards reveal and eliminate a player',()=>{const room=roomWith(4),target=room.players.find(p=>room.game.roles[p.id]==='mutin'),actor=room.players.find(p=>p.id!==target.id);for(let i=0;i<3;i++){setTurn(room,actor);room.game.hands[actor.id]=[{id:`p${i}`,type:'plank'}];act(room,actor,'playAction',{cardId:`p${i}`,target:target.id});if(room.game.phase==='finished')break}assert.ok(room.game.eliminated.includes(target.id));assert.equal(room.game.winner,'pirates')});
test('a Pirate claim reveals a sufficient chest',()=>{const room=roomWith(),pirate=room.players.find(p=>room.game.roles[p.id]==='pirate');setTurn(room,pirate);room.game.chest=Array.from({length:room.game.target},(_,i)=>({id:`c${i}`,type:'loot',value:1}));act(room,pirate,'claim');assert.equal(room.game.winner,'pirates');assert.equal(room.game.revealedChestTotal,room.game.target)});
test('mutins win at parity and when the draw pile is empty',()=>{const room=roomWith(3),mutin=room.players.find(p=>room.game.roles[p.id]==='mutin'),pirate=room.players.find(p=>room.game.roles[p.id]==='pirate');setTurn(room,mutin);room.game.hands[mutin.id]=[{id:'p',type:'plank'}];room.game.planks[pirate.id]=2;act(room,mutin,'playAction',{cardId:'p',target:pirate.id});assert.equal(room.game.winner,'mutins');const room2=roomWith(3),p=room2.players[room2.game.turnIndex];room2.game.drawPile=[];room2.game.hands[p.id]=[{id:'l',type:'loot',value:0}];act(room2,p,'playLoot',{cardId:'l',announced:0});assert.equal(room2.game.winner,'mutins')});
test('Longue-vue and Pêche miraculeuse require private ordering choices',()=>{const room=roomWith(),p=room.players[room.game.turnIndex];room.game.chest=[{id:'a',type:'loot',value:1},{id:'b',type:'loot',value:0},{id:'c',type:'loot',value:-2}];room.game.hands[p.id]=[{id:'spy',type:'spyglass'}];act(room,p,'playAction',{cardId:'spy'});assert.equal(room.game.phase,'reorder-chest');assert.equal(traitorView(room,p).game.pending.cards.length,3);act(room,p,'resolveOrder',{order:room.game.pending.cards.map(c=>c.id)});setTurn(room,p);room.game.hands[p.id]=[{id:'fish',type:'miraculousCatch'},{id:'x',type:'loot',value:1},{id:'y',type:'loot',value:0}];act(room,p,'playAction',{cardId:'fish'});assert.equal(room.game.phase,'return-draw');assert.equal(room.game.hands[p.id].length,5);act(room,p,'resolveOrder',{order:room.game.hands[p.id].slice(0,2).map(c=>c.id)});assert.equal(room.game.hands[p.id].length,3)});
