import Link from 'next/link';

export default function Home() {
  return <main className="shell">
    <header className="nav"><Link href="/" className="brand"><span className="brand-icon">✦</span> entre nous<span className="brand-dot">.</span></Link><Link href="/lobby" className="button small secondary">Rejoindre un salon ↗</Link></header>
    <section className="hero"><p className="eyebrow">LES MEILLEURES SOIRÉES COMMENCENT ICI</p><h1>Vos amis.<br/>Vos alliances.<br/><em>Leurs petits secrets.</em></h1><p className="intro">Une table, des personnalités et beaucoup de bluff.<br/>Retrouvez-vous en ligne. Le reste se joue entre vous.</p><Link className="button" href="/lobby">Créer notre salon <span>↗</span></Link><span className="hero-note">Gratuit · Sans inscription · Dans votre navigateur</span><div className="art" aria-hidden="true"><div className="orbit"/><div className="playing-card back">✦</div><div className="playing-card front"><span>?</span><b>À QUI FAIRE<br/>CONFIANCE ?</b><small>CONSEIL DES OMBRES</small></div><div className="sticker">100 %<br/>entre amis</div></div></section>
    <section className="catalog"><div className="section-heading"><div><p className="eyebrow">LE PROGRAMME DE CE SOIR</p><h2>On joue à quoi ?</h2></div><span>04 jeux disponibles</span></div><div className="game-grid catalog-two"><article className="game-card"><div className="game-illustration"><span className="tag">BLUFF & RÔLES CACHÉS</span><div className="masks" aria-hidden="true">◈ <span>◈</span> ◈</div><p>Personne n’est tout à fait<br/>celui que vous croyez.</p></div><div className="game-description"><h3>Conseil des Ombres</h3><p>Formez une équipe. Votez. Menez vos missions.<br/>Mais attention : les Ombres sont parmi vous.</p><div className="game-meta"><span>5–10 joueurs</span><span>5 missions maximum</span></div><Link className="button" href="/lobby">Jouer entre amis <span>→</span></Link></div></article><article className="game-card council-card"><div className="council-illustration"><span className="tag">ÉLECTIONS & DÉCRETS</span><div aria-hidden="true"><b>R</b><i>◆</i><b>A</b></div><p>La République<br/>retient son souffle.</p></div><div className="game-description"><h3>Le Dernier Conseil</h3><p>Élisez un gouvernement. Votez les décrets.<br/>Démasquez le Prétendant avant qu’il ne prenne le pouvoir.</p><div className="game-meta"><span>5–10 joueurs</span><span>30–45 minutes</span></div><Link className="button council-button" href="/dernier-conseil">Ouvrir la séance <span>→</span></Link></div></article><article className="game-card metro-card"><div className="metro-illustration"><span className="tag">IMMOBILIER & ITINÉRAIRES</span><div className="mini-map" aria-hidden="true"><i/><i/><i/><i/><b>◆</b><b>◆</b></div><p>Chaque détour peut<br/>bâtir votre fortune.</p></div><div className="game-description"><h3>Métropole</h3><p>Choisissez vos routes, investissez dans huit quartiers et surveillez votre trésorerie.</p><div className="game-meta"><span>2–6 joueurs</span><span>20 journées maximum</span></div><Link className="button metro-catalog-button" href="/metropole">Bâtir la ville <span>→</span></Link></div></article><article className="game-card traitor-card"><div className="traitor-illustration"><span className="tag">BLUFF & MUTINERIE</span><div className="mini-ship" aria-hidden="true">☠<i>⚓</i></div><p>Le coffre se remplit.<br/>Les mensonges aussi.</p></div><div className="game-description"><h3>Traîtres à bord !</h3><p>Ajoutez du butin face cachée, bluffez sur sa valeur et poussez les Mutins par-dessus bord.</p><div className="game-meta"><span>3–8 joueurs</span><span>20 minutes</span></div><Link className="button traitor-catalog-button" href="/traitre-a-bord">Monter à bord <span>→</span></Link></div></article></div></section>
    <section className="steps"><div><b>01</b><h3>Ouvrez la table</h3><p>Un pseudo, un clic : votre salon est prêt.</p></div><div><b>02</b><h3>Rassemblez la bande</h3><p>Partagez le code ou le lien avec vos amis.</p></div><div><b>03</b><h3>Gardez votre poker face</h3><p>Lisez votre rôle en secret et lancez les débats.</p></div></section><footer><span className="brand">entre nous.</span><span>Les bons moments se jouent à plusieurs.</span></footer>
  </main>;
}
