'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { FRONTIER_REGIONS, FRONTIER_REGION_BY_ID } from '@/lib/frontier-map.mjs';

type Player = { id: string; name: string; ready: boolean };
type Order = { id: string; type: 'move' | 'recruit'; from?: string; to?: string; region?: string; amount: number };
type Game = { phase: string; round: number; maxRounds: number; initiative: string[]; capitals: Record<string,string>; owners: Record<string,string|null>; armies: Record<string,number>; supply: Record<string,number>; myOrders: Order[]; orderCounts: Record<string,number>; locked: string[]; log: string[]; winner: string|null; reason: string|null; scores: Record<string,number> };
type Room = { code: string; host: string; me: string; players: Player[]; messages: {id:string;name:string;text:string}[]; game: Game|null };
type Session = { code: string; token: string };

const COLORS = ['#d84b39','#296bb2','#4d8c57','#d39a2e','#8057a8','#278d91'];

export default function FrontierExpress() {
  const [room,setRoom]=useState<Room|null>(null),[session,setSession]=useState<Session|null>(null);
  const [name,setName]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [from,setFrom]=useState(''),[to,setTo]=useState(''),[recruitRegion,setRecruitRegion]=useState(''),[amount,setAmount]=useState(1);
  const lock=useRef(false),revision=useRef(0);
  useEffect(()=>{const invite=new URLSearchParams(window.location.search).get('code');let saved:Session|null=null;try{const stored=JSON.parse(sessionStorage.getItem('frontieres-express')||'null');if(stored?.code&&stored?.token&&(!invite||invite.toUpperCase()===stored.code))saved=stored}catch{}queueMicrotask(()=>{if(invite)setCode(invite.toUpperCase());if(saved)setSession(saved)})},[]);
  useEffect(()=>{if(!session)return;let active=true,polling=false;const refresh=async()=>{if(lock.current||polling)return;polling=true;const rev=revision.current;try{const response=await fetch('/api/frontier',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.token}`},body:JSON.stringify({action:'state',code:session.code})}),data=await response.json();if(!active||rev!==revision.current||lock.current)return;if(!response.ok){setError(data.error);if(response.status===400){setSession(null);setRoom(null);sessionStorage.removeItem('frontieres-express')}return}setRoom(data.room);setError('')}catch{if(active&&!lock.current)setError('Liaison interrompue. Nouvelle tentative…')}finally{polling=false}};void refresh();const timer=setInterval(refresh,1400);return()=>{active=false;clearInterval(timer)}},[session]);
  async function action(actionName:string,fields:Record<string,unknown>={}){if(busy||lock.current)return;lock.current=true;revision.current++;setBusy(true);setError('');try{const response=await fetch('/api/frontier',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.token}`}:{})},body:JSON.stringify({action:actionName,code:session?.code??code,name,round:room?.game?.round??0,...fields})}),data=await response.json();if(!response.ok)throw new Error(data.error);if(data.token){const next={code:data.room.code,token:data.token};sessionStorage.setItem('frontieres-express',JSON.stringify(next));setSession(next)}setRoom(data.room);if(actionName==='chat')setMessage('');if(actionName==='move'){setFrom('');setTo('')}if(actionName==='leave'){setSession(null);sessionStorage.removeItem('frontieres-express')}}catch(err){setError(err instanceof Error?err.message:'Ordre impossible.')}finally{lock.current=false;setBusy(false)}}
  const g=room?.game,myIndex=room?.players.findIndex(player=>player.id===room.me)??0,myColor=COLORS[myIndex%COLORS.length];
  const playerName=(id?:string|null)=>room?.players.find(player=>player.id===id)?.name??'Neutre';
  const playerColor=(id?:string|null)=>id?COLORS[(room?.players.findIndex(player=>player.id===id)??0)%COLORS.length]:'#8c9189';
  const mine=FRONTIER_REGIONS.filter(region=>g?.owners[region.id]===room?.me);
  const neighbors=from?FRONTIER_REGION_BY_ID[from].links:[];
  async function copyInvite(){const url=`${window.location.origin}/frontieres-express?code=${room?.code}`;try{await navigator.clipboard.writeText(url);setNotice('Lien de campagne copié.')}catch{setNotice(url)}}
  function sendChat(e:FormEvent){e.preventDefault();void action('chat',{text:message})}
  function selectRegion(id:string){if(!g||g.phase==='finished'||g.locked.includes(room!.me))return;if(g.owners[id]===room?.me){setFrom(id);setTo('');setRecruitRegion(id)}else if(from&&neighbors.includes(id))setTo(id)}
  return <main className="frontier-shell">
    <header className="frontier-nav"><Link href="/" className="frontier-logo"><span>FX</span> FRONTIÈRES EXPRESS</Link><b>CONQUÊTE EN 8 MANCHES</b><Link href="/">← Jeux</Link></header>
    {error&&<div className="frontier-alert" role="alert">{error}</div>}
    {!room?<section className="frontier-entry"><p className="frontier-kicker">STRATÉGIE · DIPLOMATIE · 25 MINUTES</p><h1>LE MONDE<br/><em>N’ATTENDRA PAS.</em></h1><p>Deux ordres secrets par manche. Huit manches pour prendre le contrôle du continent.</p><div className="frontier-ticket"><label htmlFor="commander">Nom du commandant</label><div><input id="commander" value={name} maxLength={20} onChange={e=>setName(e.target.value)} placeholder="Votre pseudo"/><button disabled={busy||name.trim().length<2} onClick={()=>action('create')}>Créer une campagne</button></div><span>OU</span><div><input aria-label="Code de campagne" value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="CODE"/><button className="frontier-ghost" disabled={busy||name.trim().length<2||code.length!==8} onClick={()=>action('join')}>Rejoindre</button></div></div></section>:<>
      <section className="frontier-heading"><div><small>QG · CAMPAGNE {room.code}</small><h1>FRONTIÈRES EXPRESS</h1></div><button onClick={copyInvite}>Inviter des commandants ↗</button></section><p className="frontier-notice">{notice}</p>
      {!g?<section className="frontier-lobby"><div><p className="frontier-kicker">ÉTAT-MAJOR · {room.players.length}/6</p><h2>Préparez la carte.</h2><p>Chaque commandant commence avec une capitale, un territoire voisin et six points de ravitaillement.</p>{room.players.map((player,index)=><div className="frontier-player" key={player.id}><i style={{background:COLORS[index]}}/><b>{player.name}{player.id===room.me?' · VOUS':''}</b><span>{player.ready?'PRÊT':'EN ATTENTE'}</span></div>)}<div className="frontier-actions"><button onClick={()=>action('ready')}>{room.players.find(player=>player.id===room.me)?.ready?'Annuler':'Je suis prêt'}</button>{room.host===room.me&&<button className="frontier-ghost" disabled={busy||room.players.length<2||!room.players.every(player=>player.ready)} onClick={()=>action('start')}>Lancer la campagne</button>}<button className="frontier-text" onClick={()=>action('leave')}>Quitter</button></div></div><div className="frontier-preview"><b>12</b><span>RÉGIONS</span><b>2</b><span>ORDRES / MANCHE</span><b>8</b><span>MANCHES MAXIMUM</span></div></section>:<div className="frontier-layout">
        <aside className="frontier-roster"><h2>PUISSANCES</h2>{room.players.map((player,index)=>{const territories=Object.values(g.owners).filter(owner=>owner===player.id).length;return <div className={`frontier-power ${g.winner===player.id?'winner':''}`} key={player.id}><i style={{background:COLORS[index]}}/><div><b>{player.name}{player.id===room.me?' · VOUS':''}</b><small>{territories} région(s) · {g.scores[player.id]} pts</small></div><span>{g.phase==='finished'?'':g.locked.includes(player.id)?'✓':`${g.orderCounts[player.id]}/2`}</span></div>})}<div className="frontier-round"><small>MANCHE</small><b>{g.round}<i>/ {g.maxRounds}</i></b></div><div className="frontier-log"><h3>COMMUNIQUÉS</h3>{g.log.slice(0,8).map((line,index)=><p key={index}>{line}</p>)}</div></aside>
        <section className="frontier-map-panel"><div className="frontier-map-head"><div><small>CARTE TACTIQUE</small><b>Cliquez votre région, puis une voisine.</b></div><span style={{color:myColor}}>◆ {g.supply[room.me]} RAVITAILLEMENT</span></div><svg className="frontier-map" viewBox="0 0 100 100" role="img" aria-label="Carte stratégique de douze régions">
          {FRONTIER_REGIONS.flatMap((region,index)=>region.links.filter(link=>index<FRONTIER_REGIONS.findIndex(item=>item.id===link)).map(link=>{const other=FRONTIER_REGION_BY_ID[link];return <line key={`${region.id}-${link}`} x1={region.x} y1={region.y} x2={other.x} y2={other.y}/> }))}
          {FRONTIER_REGIONS.map(region=>{const owner=g.owners[region.id],selected=from===region.id||to===region.id,available=from&&neighbors.includes(region.id);return <g key={region.id} className={`${selected?'selected ':''}${available?'available ':''}`} onClick={()=>selectRegion(region.id)} role="button" aria-label={`${region.name}, ${g.armies[region.id]} unités, ${playerName(owner)}`}><circle cx={region.x} cy={region.y} r="7.4" fill={playerColor(owner)}/><text className="region-name" x={region.x} y={region.y-1.3}>{region.name}</text><text className="army" x={region.x} y={region.y+3.8}>{g.capitals[owner??'']===region.id?'★ ':''}{g.armies[region.id]}</text></g>})}
        </svg><div className="frontier-legend"><span>★ capitale</span><span>Le chiffre indique les unités</span><span>7 régions contrôlées = victoire immédiate</span></div></section>
        <aside className="frontier-orders">{g.phase==='finished'?<div className="frontier-victory"><small>FIN DE CAMPAGNE</small><h2>{playerName(g.winner)} l’emporte</h2><p>{g.reason}</p>{room.host===room.me&&<button onClick={()=>action('reset')}>Nouvelle campagne</button>}</div>:g.locked.includes(room.me)?<div className="frontier-locked"><b>ORDRES TRANSMIS</b><p>En attente de {room.players.filter(player=>!g.locked.includes(player.id)).map(player=>player.name).join(', ')||'la résolution'}.</p></div>:<><h2>VOS ORDRES</h2><p>Préparez jusqu’à deux actions. Elles restent secrètes jusqu’à la résolution.</p><div className="order-form"><h3>⚔ DÉPLACER / ATTAQUER</h3><select value={from} onChange={e=>{setFrom(e.target.value);setTo('')}}><option value="">Région de départ</option>{mine.map(region=><option key={region.id} value={region.id}>{region.name} · {g.armies[region.id]} unités</option>)}</select><select value={to} disabled={!from} onChange={e=>setTo(e.target.value)}><option value="">Destination voisine</option>{neighbors.map(id=><option key={id} value={id}>{FRONTIER_REGION_BY_ID[id].name} · {g.armies[id]} unités</option>)}</select><input aria-label="Nombre d’unités" type="number" min="1" max="9" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><button disabled={!from||!to||g.myOrders.length>=2} onClick={()=>action('move',{from,to,amount})}>Ajouter l’ordre</button></div><div className="order-form"><h3>✚ RECRUTER</h3><select value={recruitRegion} onChange={e=>setRecruitRegion(e.target.value)}><option value="">Votre région</option>{mine.map(region=><option key={region.id} value={region.id}>{region.name}</option>)}</select><button disabled={!recruitRegion||g.supply[room.me]<amount||g.myOrders.length>=2} onClick={()=>action('recruit',{region:recruitRegion,amount:Math.min(3,amount)})}>Recruter {Math.min(3,amount)} unité(s)</button></div><div className="order-list">{g.myOrders.length===0&&<p>Aucun ordre préparé.</p>}{g.myOrders.map(order=><div key={order.id}><span>{order.type==='move'?`${FRONTIER_REGION_BY_ID[order.from!].name} → ${FRONTIER_REGION_BY_ID[order.to!].name} · ${order.amount}`:`Recruter à ${FRONTIER_REGION_BY_ID[order.region!].name} · ${order.amount}`}</span><button onClick={()=>action('cancel',{orderId:order.id})}>×</button></div>)}</div><button className="lock-orders" onClick={()=>action('lock')}>Confirmer mes ordres ({g.myOrders.length}/2)</button></>}
          <div className="frontier-chat"><h3>CANAL DIPLOMATIQUE</h3><div>{room.messages.slice(-20).map(item=><p key={item.id}><b>{item.name}</b>{item.text}</p>)}</div><form onSubmit={sendChat}><input aria-label="Message diplomatique" value={message} maxLength={400} onChange={e=>setMessage(e.target.value)} placeholder="Négocier une trêve…"/><button disabled={!message.trim()}>↑</button></form></div></aside>
      </div>}
    </>}
    <details className="frontier-rules"><summary>Règles de Frontières Express</summary><div><p>Chaque manche, tous les commandants préparent secrètement deux ordres au maximum : recruter ou déplacer des unités vers une région voisine. Il faut toujours laisser une unité dans la région de départ.</p><p>Les recrutements sont appliqués avant les mouvements. Une attaque réussit si elle engage plus d’unités que la défense. Chaque nouvelle manche rapporte un point de ravitaillement par région et deux points supplémentaires si votre capitale est toujours sous votre contrôle.</p><p>Contrôlez sept régions pour gagner immédiatement. Sinon, après huit manches, le score additionne les territoires, les unités et le ravitaillement restant.</p></div></details>
  </main>;
}
