'use client';
import Link from 'next/link';
import { FormEvent, useEffect, useRef, useState } from 'react';

type Player = { id:string; name:string; ready:boolean; alive:boolean };
type History = { type:string; policy?:'republique'|'autorite'; chaos?:boolean; president?:string; speaker?:string; approved?:boolean; votes?:Record<string,boolean> };
type CouncilGame = { phase:string; president:string; nominee:string|null; role:'gardien'|'conspirateur'|'pretendant'; knownConspirators:string[]; policies:{republique:number;autorite:number}; failed:number; history:History[]; voted:string[]; hand:('republique'|'autorite')[]; power:string|null; privateIntel:{target:string;affiliation:string}|null; winner?:string; reason?:string; pretender:string|null; vetoAvailable:boolean };
type Room = { code:string;host:string;me:string;players:Player[];messages:{id:string;name:string;text:string}[];game:CouncilGame|null };
type Session = { code:string;token:string };

export default function LastCouncil() {
  const [room,setRoom]=useState<Room|null>(null); const [session,setSession]=useState<Session|null>(null);
  const [name,setName]=useState(''); const [code,setCode]=useState(''); const [message,setMessage]=useState('');
  const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false); const [reveal,setReveal]=useState(false);
  const requestLock=useRef(false); const revision=useRef(0);
  useEffect(()=>{ const invite=new URLSearchParams(window.location.search).get('code'); let saved:Session|null=null; try{saved=JSON.parse(sessionStorage.getItem('dernier-conseil')||'null')}catch{} queueMicrotask(()=>{if(invite)setCode(invite.toUpperCase());if(saved?.code&&saved?.token&&(!invite||invite.toUpperCase()===saved.code))setSession(saved)}); },[]);
  useEffect(()=>{if(!session)return;let active=true,polling=false;const refresh=async()=>{if(requestLock.current||polling)return;polling=true;const rev=revision.current;try{const response=await fetch('/api/council',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.token}`},body:JSON.stringify({action:'state',code:session.code})});const data=await response.json();if(!active||rev!==revision.current||requestLock.current)return;if(!response.ok){setError(data.error);if(response.status===400){setSession(null);setRoom(null);sessionStorage.removeItem('dernier-conseil');}return;}setRoom(data.room);setError('');}catch{if(active&&rev===revision.current&&!requestLock.current)setError('Connexion interrompue. Nouvelle tentative…');}finally{polling=false;}};void refresh();const timer=setInterval(refresh,1500);return()=>{active=false;clearInterval(timer)}},[session]);
  async function action(actionName:string,fields:Record<string,unknown>={}){if(busy||requestLock.current)return;requestLock.current=true;revision.current++;setBusy(true);setError('');try{const response=await fetch('/api/council',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.token}`}:{})},body:JSON.stringify({action:actionName,code:session?.code??code,name,revision:room?.game?.history.length??0,...fields})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(data.token){const next={code:data.room.code,token:data.token};sessionStorage.setItem('dernier-conseil',JSON.stringify(next));setSession(next);}setRoom(data.room);if(actionName==='chat')setMessage('');if(['start','reset','leave'].includes(actionName))setReveal(false);if(actionName==='leave'){setSession(null);sessionStorage.removeItem('dernier-conseil');}}catch(err){setError(err instanceof Error?err.message:'Impossible de contacter le serveur.')}finally{requestLock.current=false;setBusy(false)}}
  const g=room?.game; const me=room?.players.find(p=>p.id===room.me); const nameOf=(id?:string|null)=>room?.players.find(p=>p.id===id)?.name??'?';
  const lastElection=g?.history.filter(h=>h.type==='election').at(-1); const livingCount=room?.players.filter(p=>p.alive).length??0;
  const eligible=room?.players.filter(p=>p.alive&&p.id!==g?.president&&p.id!==lastElection?.speaker&&(livingCount<=5||p.id!==lastElection?.president))??[];
  async function copyInvite(){const url=`${window.location.origin}/dernier-conseil?code=${room?.code}`;try{await navigator.clipboard.writeText(url);setNotice('Lien d’invitation copié.')}catch{setNotice(url)}}
  function sendChat(e:FormEvent){e.preventDefault();void action('chat',{text:message})}
  const roleText=g?.role==='gardien'?'Gardien de la République':g?.role==='conspirateur'?'Conspirateur':'Prétendant';
  const phaseTitle=()=>g?.phase==='nomination'?'Former le gouvernement':g?.phase==='vote'?'L’assemblée doit voter':g?.phase==='legislation-president'?'Trois décrets sur le bureau':g?.phase==='legislation-speaker'?'Le dernier mot appartient à l’Orateur':g?.phase==='veto'?'Le veto est demandé':g?.phase==='power'?'Pouvoir exceptionnel':'La séance est levée';
  const policyCard=(policy:'republique'|'autorite',index:number,actor:'president'|'speaker')=><button key={index} className={`decree ${policy}`} disabled={busy} onClick={()=>action(actor==='president'?'discard-president':'discard-speaker',{index})}><span>{policy==='republique'?'R':'A'}</span><b>{policy==='republique'?'RÉPUBLIQUE':'AUTORITÉ'}</b><small>{actor==='president'?'Écarter ce décret':'Écarter et promulguer l’autre'}</small></button>;
  return <main className={`assembly-shell ${g?'assembly-live':''}`}><header className="assembly-nav"><Link href="/" className="assembly-brand"><span>DC</span> ENTRE NOUS</Link><b>LE DERNIER CONSEIL</b><Link href="/" className="back-link">← Jeux</Link></header>
    {error&&<div className="assembly-alert" role="alert">{error}</div>}
    {!room?<section className="assembly-entry"><div className="poster-mark">◆</div><p className="kicker">UNE ASSEMBLÉE · DEUX CAMPS · UN PRÉTENDANT</p><h1>LE DERNIER<br/><i>CONSEIL</i></h1><p>La République vacille. Prenez place, votez les décrets<br/>et découvrez qui prépare sa chute.</p><div className="entry-ticket"><label htmlFor="council-name">Nom du délégué</label><input id="council-name" value={name} minLength={2} maxLength={20} onChange={e=>setName(e.target.value)} placeholder="Votre pseudo"/><div><button disabled={busy||name.trim().length<2} onClick={()=>action('create')}>Convoquer l’assemblée</button><span>OU</span><input aria-label="Code de l’assemblée" value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="CODE"/><button className="cream" disabled={busy||name.trim().length<2||code.length!==8} onClick={()=>action('join')}>Prendre place</button></div></div></section>:<>
    <section className="assembly-masthead"><div><p>SESSION EXTRAORDINAIRE · ACCÈS PRIVÉ</p><h1>LE DERNIER CONSEIL</h1></div><div className="session-code"><small>CODE DE SESSION</small><b>{room.code}</b><button onClick={copyInvite}>Inviter ↗</button></div></section><p className="assembly-notice" role="status">{notice}</p>
    <div className="assembly-layout"><aside className="delegates"><h2>DÉLÉGUÉS <span>{room.players.filter(p=>p.alive).length}/{room.players.length}</span></h2>{room.players.map((p,i)=><div className={`delegate ${!p.alive?'banished':''}`} key={p.id}><span>{String(i+1).padStart(2,'0')}</span><div><b>{p.name}{p.id===room.me?' · VOUS':''}</b><small>{!p.alive?'BANNI':p.id===g?.president?'PREMIER CONSEILLER':p.id===g?.nominee?'ORATEUR':p.id===room.host?'HÔTE':'DÉLÉGUÉ'}</small></div>{!g&&p.ready&&<i>PRÊT</i>}</div>)}{(!g||g.phase==='finished')&&<button className="text-button" onClick={()=>action('leave')}>Quitter l’assemblée</button>}</aside>
    <section className="assembly-board">{!g?<div className="waiting-session"><p className="kicker">AVANT L’OUVERTURE DE LA SÉANCE</p><h2>QUI DÉFENDRA<br/>LA RÉPUBLIQUE ?</h2><div className="faction-seals"><span>R</span><b>?</b><span>A</span></div><p>Il faut entre 5 et 10 délégués. Chacun doit confirmer sa présence.</p><div className="assembly-actions"><button onClick={()=>action('ready')}>{me?.ready?'Annuler ma présence':'Confirmer ma présence'}</button>{room.host===room.me&&<button className="cream" disabled={busy||room.players.length<5||!room.players.every(p=>p.ready)} onClick={()=>action('start')}>Ouvrir la séance →</button>}</div></div>:<>
      <div className="policy-tracks"><div className="track republic"><header><b>RÉPUBLIQUE</b><strong>{g.policies.republique}/6</strong></header><div>{[0,1,2,3,4,5].map(i=><span className={i<g.policies.republique?'filled':''} key={i}>◆</span>)}</div></div><div className="track authority"><header><b>AUTORITÉ</b><strong>{g.policies.autorite}/6</strong></header><div>{[0,1,2,3,4,5].map(i=><span className={i<g.policies.autorite?'filled':''} key={i}>{i===1?'Œ':i===2?'↻':i>=3?'×':'◆'}</span>)}</div></div></div>
      <div className="secret-file"><button onClick={()=>setReveal(!reveal)}>{reveal?'Refermer mon dossier':'Consulter mon rôle secret'}</button>{reveal&&<div><p>VOTRE IDENTITÉ</p><h3>{roleText}</h3><p>{g.role==='gardien'?'Faites adopter six décrets républicains ou bannissez le Prétendant.':g.role==='pretendant'?'Restez discret. Après trois décrets d’autorité, faites-vous élire Orateur.':`Protégez le Prétendant et faites adopter six décrets d’autorité. Alliés connus : ${g.knownConspirators.map(nameOf).join(', ')}.`}</p>{g.privateIntel&&<p className="intel">RENSEIGNEMENT : {nameOf(g.privateIntel.target)} sert la {g.privateIntel.affiliation}.</p>}</div>}</div>
      {g.phase==='finished'?<div className={`verdict ${g.winner}`}><p>VERDICT OFFICIEL</p><h2>{g.winner==='republique'?'LA RÉPUBLIQUE TIENT BON':'LA CONSPIRATION TRIOMPHE'}</h2><p>{g.reason}</p><p>Le Prétendant était <b>{nameOf(g.pretender)}</b>.</p>{room.host===room.me&&<button onClick={()=>action('reset')}>Convoquer une revanche</button>}</div>:<div className="session-action"><p className="kicker">GOUVERNEMENT · {g.failed}/3 ÉLECTIONS REFUSÉES</p><h2>{phaseTitle()}</h2>
        {g.phase==='nomination'&&<><p><b>{nameOf(g.president)}</b> préside la séance et doit désigner un Orateur.</p>{g.president===room.me&&<div className="candidate-grid">{eligible.map(p=><button key={p.id} onClick={()=>action('nominate',{player:p.id})}>{p.name}<small>Nommer Orateur</small></button>)}</div>}</>}
        {g.phase==='vote'&&<><div className="government"><span>{nameOf(g.president)}<small>Premier Conseiller</small></span><b>+</b><span>{nameOf(g.nominee)}<small>Orateur proposé</small></span></div><p>{g.voted.length}/{room.players.filter(p=>p.alive).length} bulletins déposés.</p>{g.voted.includes(room.me)?<p className="status-stamp">BULLETIN DÉPOSÉ</p>:<div className="assembly-actions"><button onClick={()=>action('vote',{approve:true})}>POUR</button><button className="cream" onClick={()=>action('vote',{approve:false})}>CONTRE</button></div>}</>}
        {g.phase==='legislation-president'&&<>{g.president===room.me?<><p>Écartez un décret. Les deux autres seront transmis secrètement à l’Orateur.</p><div className="decree-hand">{g.hand.map((p,i)=>policyCard(p,i,'president'))}</div></>:<p>Le Premier Conseiller examine trois décrets en secret…</p>}</>}
        {g.phase==='legislation-speaker'&&<>{g.nominee===room.me?<><p>Écartez un décret. Le décret restant sera immédiatement promulgué.</p><div className="decree-hand">{g.hand.map((p,i)=>policyCard(p,i,'speaker'))}</div>{g.vetoAvailable&&<button className="veto" onClick={()=>action('request-veto')}>Demander le veto</button>}</>:<p>L’Orateur choisit le décret qui entrera dans l’Histoire…</p>}</>}
        {g.phase==='veto'&&<>{g.president===room.me?<><p>L’Orateur demande d’écarter les deux décrets. Accepter compte comme une élection refusée.</p><div className="assembly-actions"><button onClick={()=>action('answer-veto',{approve:true})}>Accepter le veto</button><button className="cream" onClick={()=>action('answer-veto',{approve:false})}>Refuser</button></div></>:<p>Le Premier Conseiller examine la demande de veto…</p>}</>}
        {g.phase==='power'&&<>{g.president===room.me?<><p>{g.power==='inspect'?'Consultez secrètement l’allégeance d’un délégué.':g.power==='special-election'?'Choisissez le prochain Premier Conseiller.':'Bannissez un délégué de l’assemblée.'}</p><div className="candidate-grid">{room.players.filter(p=>p.alive&&p.id!==room.me).map(p=><button key={p.id} onClick={()=>action('power',{player:p.id})}>{p.name}<small>{g.power==='inspect'?'Inspecter':g.power==='special-election'?'Élire':'Bannir'}</small></button>)}</div></>:<p>Le Premier Conseiller exerce son pouvoir exceptionnel…</p>}</>}
      </div>}
      {g.history.length>0&&<details className="gazette"><summary>Lire la gazette de la séance ({g.history.length})</summary>{g.history.slice().reverse().map((h,i)=><p key={i}>{h.type==='policy'?<><b>Décret {h.policy==='republique'?'républicain':'d’autorité'}</b>{h.chaos?' adopté par le chaos électoral.':` promulgué par ${nameOf(h.president)} et ${nameOf(h.speaker)}.`}</>:<><b>Gouvernement {h.approved?'élu':'rejeté'}</b> — {nameOf(h.president)} avec {nameOf(h.speaker)}.</>}</p>)}</details>}
    </>}</section>
    <aside className="assembly-chat"><h2>COULOIRS</h2><div aria-live="polite">{room.messages.length===0&&<p>Les murmures commencent ici…</p>}{room.messages.map(m=><p key={m.id}><b>{m.name}</b>{m.text}</p>)}</div><form onSubmit={sendChat}><label className="sr-only" htmlFor="council-message">Message</label><input id="council-message" maxLength={400} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Votre déclaration…"/><button disabled={busy||!message.trim()}>↑</button></form></aside></div></>}
    <details className="assembly-rules"><summary>Règlement officiel du Dernier Conseil</summary><div><p>Les Gardiens sont majoritaires. Les Conspirateurs connaissent leur camp ; à 7 joueurs ou plus, le Prétendant ne connaît pas ses alliés. Un gouvernement élu traite trois décrets : le Premier Conseiller en écarte un, puis l’Orateur en écarte un.</p><p>Six décrets républicains ou le bannissement du Prétendant donnent la victoire à la République. Six décrets d’autorité, ou l’élection du Prétendant comme Orateur après trois décrets d’autorité, donnent la victoire à la Conspiration. Trois élections refusées promulguent automatiquement le prochain décret.</p></div></details>
  </main>;
}
