'use client';
import { useEffect, useRef, useState } from 'react';
type Asset={id:string;name:string;group?:string;price?:number;type:string};
type Offer={id:string;from:string;to:string;offerNode?:string;wantNode?:string;offerNodes?:string[];wantNodes?:string[];offerCash?:number;wantCash?:number};
type Props={game:{phase:string;money:Record<string,number>;owners:Record<string,string>;bankrupt:string[];houses:Record<string,number>;mortgages:Record<string,boolean>;tradeOffers:Offer[]};players:{id:string;name:string}[];me:string;assets:Record<string,Asset>;colors:Record<string,string>;busy:boolean;action:(action:string,data?:Record<string,unknown>)=>Promise<unknown>};
export default function MetroTradeDesk({game:g,players,me,assets,colors,busy,action}:Props){
 const [sendError,setSendError]=useState('');
 const [open,setOpen]=useState(false),[target,setTarget]=useState(''),[give,setGive]=useState<string[]>([]),[take,setTake]=useState<string[]>([]),[giveCash,setGiveCash]=useState(0),[takeCash,setTakeCash]=useState(0);
 const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 const name=(id:string)=>players.find(p=>p.id===id)?.name??'Investisseur';
 const ids=(o:Offer,side:'offer'|'want')=>o[side+'Nodes' as 'offerNodes'|'wantNodes']??(o[side+'Node' as 'offerNode'|'wantNode']?[o[side+'Node' as 'offerNode'|'wantNode']!]:[]);
 const blocked=busy||g.bankrupt.includes(me)||['auction','debt'].includes(g.phase);
 const close=()=>{setOpen(false);trigger.current?.focus();};
 const start=()=>{setSendError('');setTarget(players.find(p=>p.id!==me&&!g.bankrupt.includes(p.id))?.id??'');setGive([]);setTake([]);setGiveCash(0);setTakeCash(0);setOpen(true);};
 const summary=(o:Offer,side:'offer'|'want')=>[...ids(o,side).map(id=>assets[id]?.name??id),((side==='offer'?o.offerCash:o.wantCash)??0)+' M'].join(' + ');
 function column(owner:string,selected:string[],setSelected:(ids:string[])=>void,cash:number,setCash:(n:number)=>void,label:string){return <section className="trade-side"><h3>{name(owner)}{owner===me?' (vous)':''}</h3><p>Trésorerie : {g.money[owner]??0} M</p><label>{label}<input type="range" min="0" max={Math.max(0,g.money[owner]??0)} step="1" value={cash} onChange={e=>setCash(Number(e.target.value))}/><span className="trade-cash"><input aria-label={label+' en M'} type="number" min="0" max={Math.max(0,g.money[owner]??0)} step="1" value={cash} onChange={e=>setCash(Math.max(0,Math.floor(Number(e.target.value)||0)))}/> M</span></label><div className="trade-properties">{Object.entries(g.owners).filter(([,id])=>id===owner).map(([id])=><button type="button" key={id} aria-pressed={selected.includes(id)} className={selected.includes(id)?'selected':''} style={{'--trade-color':colors[assets[id]?.group??'']??(assets[id]?.type==='station'?'#7623df':'#43d3d4')} as React.CSSProperties} onClick={()=>setSelected(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id])}><b>{selected.includes(id)?'✓ ':''}{assets[id]?.name}</b><span>{assets[id]?.price??220} M{g.mortgages[id]?' · Hypothéqué':''}{g.houses[id]?' · '+g.houses[id]+' maison(s)':''}</span></button>)}{!Object.values(g.owners).includes(owner)&&<p>Aucun bien. Vous pouvez proposer de l’argent.</p>}</div></section>;}
 return <div className="trade-desk"><h3>NÉGOCIER DES BIENS ET DE L’ARGENT</h3><p>Composez librement chaque côté de votre offre.</p><button ref={trigger} disabled={blocked||players.filter(p=>!g.bankrupt.includes(p.id)).length<2} onClick={start}>Créer un échange</button>{['auction','debt'].includes(g.phase)&&<p>Échanges disponibles après les enchères ou le règlement de la dette.</p>}{g.tradeOffers.map(o=><div className="trade-offer" key={o.id}><b>{name(o.from)} ⇄ {name(o.to)}</b><span>{name(o.from)} donne : {summary(o,'offer')}</span><span>{name(o.to)} donne : {summary(o,'want')}</span>{o.to===me&&<div><button disabled={blocked} onClick={()=>action('accept-trade',{offerId:o.id})}>Accepter</button><button disabled={busy} className="metro-light" onClick={()=>action('reject-trade',{offerId:o.id})}>Refuser</button></div>}{o.from===me&&<button disabled={busy} className="metro-light" onClick={()=>action('reject-trade',{offerId:o.id})}>Annuler</button>}</div>)}
 <dialog ref={dialog} className="metro-trade-dialog" aria-labelledby="trade-title" onCancel={close} onClose={()=>setOpen(false)}><header><div><small>CAFÉ DES AFFAIRES</small><h2 id="trade-title">Créer un échange</h2></div><button className="metro-light" onClick={close} aria-label="Fermer l’échange">✕</button></header><label className="trade-partner">Négocier avec<select value={target} onChange={e=>{setTarget(e.target.value);setTake([]);setTakeCash(0);}}>{players.filter(p=>p.id!==me&&!g.bankrupt.includes(p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="trade-columns">{column(me,give,setGive,giveCash,setGiveCash,'Argent proposé')}<div className="trade-arrows" aria-hidden="true">⇄</div>{column(target,take,setTake,takeCash,setTakeCash,'Argent demandé')}</div><footer><p>Vous donnez <b>{give.length} bien(s) + {giveCash} M</b> et recevez <b>{take.length} bien(s) + {takeCash} M</b>.</p><p>Les maisons et hypothèques restent attachées aux biens. Le destinataire doit accepter.</p><p className="trade-error" role="alert">{sendError}</p><button disabled={blocked||!target||(!give.length&&!take.length&&!giveCash&&!takeCash)||giveCash>(g.money[me]??0)||takeCash>(g.money[target]??0)||give.some(id=>g.owners[id]!==me)||take.some(id=>g.owners[id]!==target)} onClick={async()=>{const result=await action('propose-trade',{to:target,offerNodes:give,wantNodes:take,offerCash:giveCash,wantCash:takeCash});if(result)close();else setSendError('L’offre n’a pas été envoyée. Vérifiez les fonds et les biens, puis réessayez.');}}>Envoyer l’offre</button></footer></dialog></div>;
}
