'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useRef,useState } from 'react';

type Player={id:string;name:string;ready:boolean};
type Game={phase:string;round:number;ejected:string[];taskProgress:number;taskTarget:number;sabotage:number;winner:string|null;history:{round:number;tasks:number;sabotages:number;ejected:string|null}[];acted:string[];voted:string[];role:'crew'|'traitor';traitors:string[]};
type Room={code:string;host:string;me:string;players:Player[];messages:{id:string;name:string;text:string}[];game:Game|null};
type Session={code:string;token:string};

export default function TraitorAboard(){
  const[room,setRoom]=useState<Room|null>(null);const[session,setSession]=useState<Session|null>(null);const[name,setName]=useState('');const[code,setCode]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[reveal,setReveal]=useState(false);const lock=useRef(false);const revision=useRef(0);
useEffect(()=>{const invite=new URLSearchParams(window.location.search).get('code');let saved:Session|null=null;try{const stored=JSON.parse(sessionStorage.getItem('traitre-a-bord')||'null');if(stored?.code&&stored?.token&&(!invite||invite.toUpperCase()===stored.code))saved=stored}catch{}queueMicrotask(()=>{if(invite)setCode(invite.toUpperCase());if(saved)setSession(saved)})},[]);
  useEffect(()=>{if(!session)return;let active=true,polling=false;const refresh=async()=>{if(lock.current||polling)return;polling=true;const rev=revision.current;try{const response=await fetch('/api/traitor',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.token}`},body:JSON.stringify({action:'state',code:session.code})});const data=await response.json();if(!active||rev!==revision.current||lock.current)return;if(!response.ok){setError(data.error);if(response.status===400){setRoom(null);setSession(null);sessionStorage.removeItem('traitre-a-bord')}return}setRoom(data.room);setError('')}catch{if(active&&!lock.current)setError('Transmission interrompue. Nouvelle tentative…')}finally{polling=false}};void refresh();const timer=setInterval(refresh,1400);return()=>{active=false;clearInterval(timer)}},[session]);
  async function action(actionName:string,fields:Record<string,unknown>={}){if(busy||lock.current)return;lock.current=true;revision.current++;setBusy(true);setError('');try{const response=await fetch('/api/traitor',{method:'POST',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session.token}`}:{})},body:JSON.stringify({action:actionName,code:session?.code??code,name,round:room?.game?.round??0,phase:room?.game?.phase??'',...fields})});const data=await response.json();if(!response.ok)throw new Error(data.error);if(data.token){const next={code:data.room.code,token:data.token};sessionStorage.setItem('traitre-a-bord',JSON.stringify(next));setSession(next)}setRoom(data.room);if(actionName==='chat')setMessage('');if(actionName==='leave'){setSession(null);sessionStorage.removeItem('traitre-a-bord')}}catch(err){setError(err instanceof Error?err.message:'Action impossible.')}finally{lock.current=false;setBusy(false)}}
  const g=room?.game;const playerName=(id?:string|null)=>room?.players.find(p=>p.id===id)?.name??'?';const me=room?.players.find(p=>p.id===room.me);const alive=!g?.ejected.includes(room?.me??'');
  async function copyInvite(){const url=`${window.location.origin}/traitre-a-bord?code=${room?.code}`;try{await navigator.clipboard.writeText(url);setNotice('Lien de mission copié.')}catch{setNotice(url)}}
  function submitChat(e:FormEvent){e.preventDefault();void action('chat',{text:message})}
  return <main className="traitor-shell">
    <header className="traitor-nav"><Link href="/" className="traitor-brand"><span>▲</span> LE TRAÎTRE À BORD</Link><b>SIGNAL // ORION-7</b><Link href="/">← Jeux</Link></header>
    {error&&<div className="traitor-alert" role="alert">{error}</div>}
    {!room?<section className="traitor-entry"><div className="ship-window" aria-hidden="true"><span>✦</span><i>ORION-7</i></div><p className="signal">COOPÉRATION · DÉDUCTION · SABOTAGE</p><h1>QUELQU’UN<br/><em>MENT À BORD.</em></h1><p>Réparez le vaisseau, surveillez l’équipage et expulsez le traître avant la panne totale.</p><div className="traitor-console"><label htmlFor="crew-name">Nom de l’équipier</label><input id="crew-name" value={name} maxLength={20} onChange={e=>setName(e.target.value)} placeholder="Votre indicatif"/><button disabled={busy||name.trim().length<2} onClick={()=>action('create')}>Créer une mission</button><span>OU</span><input aria-label="Code de mission" value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase().replace(/\s/g,''))} placeholder="CODE"/><button disabled={busy||name.trim().length<2||code.length!==8} onClick={()=>action('join')}>Rejoindre</button></div></section>:<>
      <section className="traitor-heading"><div><small>MISSION {room.code}</small><h1>ORION-7</h1></div><button onClick={copyInvite}>Inviter l’équipage ↗</button></section><p className="traitor-notice">{notice}</p>
      <div className="traitor-grid"><aside className="crew-panel"><h2>ÉQUIPAGE · {room.players.length}/10</h2>{room.players.map((p,i)=><div className={`crew-member ${g?.ejected.includes(p.id)?'ejected':''}`} key={p.id}><span style={{'--crew-color':['#5dd6ff','#ffca55','#ef6d70','#70df9c','#ab82ff','#ff8bd4'][i%6]} as React.CSSProperties}>{p.name.slice(0,1).toUpperCase()}</span><div><b>{p.name}{p.id===room.me?' · VOUS':''}</b><small>{p.id===room.host?'COMMANDANT':'ÉQUIPIER'}{g?.ejected.includes(p.id)?' · EXPULSÉ':''}</small></div>{!g&&p.ready&&<i>PRÊT</i>}</div>)}{(!g||g.phase==='finished')&&<button className="ghost" onClick={()=>action('leave')}>Quitter le vaisseau</button>}</aside>
      <section className="mission-panel">{!g?<><p className="signal">BRIEFING AVANT DÉCOLLAGE</p><h2>Préparez la mission.</h2><p>Il faut 4 à 10 joueurs. L’équipage doit réparer le vaisseau ; un ou deux traîtres tenteront de provoquer trois sabotages.</p><div className="reactor idle"><b>◉</b><span>RÉACTEUR EN VEILLE</span></div><div className="mission-actions"><button onClick={()=>action('ready')}>{me?.ready?'Annuler ma disponibilité':'Je suis prêt'}</button>{room.host===room.me&&<button className="warning" disabled={busy||room.players.length<4||!room.players.every(p=>p.ready)} onClick={()=>action('start')}>Lancer la mission</button>}</div></>:<>
        <div className="mission-stats"><div><small>RÉPARATIONS</small><b>{g.taskProgress}/{g.taskTarget}</b><progress value={g.taskProgress} max={g.taskTarget}/></div><div className="danger-meter"><small>SABOTAGES</small><b>{g.sabotage}/3</b><progress value={g.sabotage} max={3}/></div><span>ROTATION {g.round}</span></div>
        <div className={`identity ${g.role==='traitor'?'red':''}`}><button onClick={()=>setReveal(!reveal)}>{reveal?'Masquer mon dossier':'Consulter mon dossier secret'}</button>{reveal&&<p>Vous êtes <strong>{g.role==='traitor'?'LE TRAÎTRE':'MEMBRE D’ÉQUIPAGE'}</strong>. {g.role==='traitor'?`Vos alliés : ${g.traitors.map(playerName).join(', ')}. Sabotez sans attirer les soupçons.`:'Accomplissez les réparations et observez les incohérences.'}</p>}</div>
        {g.phase==='tasks'&&<div className="duty"><p className="signal">PHASE DE MAINTENANCE</p><h2>Choisissez votre intervention.</h2>{!alive?<p>Vous observez la mission depuis le sas.</p>:g.acted.includes(room.me)?<p className="confirmed">Décision enregistrée. Attendez le reste de l’équipage.</p>:<div className="duty-grid"><button onClick={()=>action('duty',{choice:'task'})}><b>⚙</b><span>Effectuer une réparation<small>Navigation, communications ou réacteur</small></span></button>{g.role==='traitor'&&<button className="sabotage" onClick={()=>action('duty',{choice:'sabotage'})}><b>⚠</b><span>Saboter discrètement<small>Le troisième sabotage détruit la mission</small></span></button>}</div>}<p>{g.acted.length}/{room.players.length-g.ejected.length} interventions reçues</p></div>}
        {g.phase==='meeting'&&<div className="meeting"><p className="signal">RÉUNION D’URGENCE</p><h2>Qui met le vaisseau en danger ?</h2>{!alive?<p>Les expulsés ne votent plus.</p>:g.voted.includes(room.me)?<p className="confirmed">Vote transmis.</p>:<div className="vote-grid">{room.players.filter(p=>!g.ejected.includes(p.id)&&p.id!==room.me).map(p=><button key={p.id} onClick={()=>action('vote',{target:p.id})}>Expulser {p.name}</button>)}<button className="ghost" onClick={()=>action('vote',{target:'skip'})}>Ne pas expulser</button></div>}<p>{g.voted.length}/{room.players.length-g.ejected.length} votes reçus</p></div>}
        {g.phase==='finished'&&<div className={`mission-end ${g.winner==='traitors'?'lost':''}`}><p className="signal">FIN DE TRANSMISSION</p><h2>{g.winner==='crew'?'L’équipage sauve Orion-7 !':'Les traîtres prennent le contrôle.'}</h2><p>Traître{g.traitors.length>1?'s':''} : {g.traitors.map(playerName).join(', ')}.</p>{room.host===room.me&&<button onClick={()=>action('reset')}>Nouvelle mission</button>}</div>}
        {g.history.length>0&&<details><summary>Journal de bord</summary>{g.history.map(h=><p key={h.round}><b>Rotation {h.round}</b> · {h.tasks} réparation(s) · {h.sabotages} sabotage(s) · {h.ejected?`${playerName(h.ejected)} expulsé`:'aucune expulsion'}</p>)}</details>}
      </>}</section>
      <aside className="comms-panel"><h2>COMMUNICATIONS</h2><div>{room.messages.length===0&&<p>Canal ouvert. Aucun message.</p>}{room.messages.map(m=><p key={m.id}><b>{m.name}</b>{m.text}</p>)}</div><form onSubmit={submitChat}><input aria-label="Message" value={message} maxLength={400} onChange={e=>setMessage(e.target.value)} placeholder="Transmettre…"/><button disabled={busy||!message.trim()}>↑</button></form></aside></div></>}
    <details className="traitor-rules"><summary>Comment jouer au Traître à bord ?</summary><ol><li>Chaque rotation, les membres accomplissent une réparation. Les traîtres peuvent réparer pour se couvrir ou saboter.</li><li>Après les interventions, l’équipage se réunit et vote. Une égalité ou le vote « ne pas expulser » laisse tout le monde à bord.</li><li>L’équipage gagne en terminant toutes les réparations ou en expulsant tous les traîtres.</li><li>Les traîtres gagnent avec trois sabotages ou lorsqu’ils sont aussi nombreux que les membres encore à bord.</li></ol></details>
  </main>
}
