import { randomBytes, randomInt, randomUUID } from 'node:crypto';
import { EVENT_CARDS, NODE_BY_ID, ROUTES, STATIONS } from '../lib/metro-board.mjs';

export class MetroError extends Error {}
const ensure=(condition,message)=>{if(!condition)throw new MetroError(message)};
const clean=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
const makePlayer=(name)=>{name=clean(name,20);ensure(name.length>=2,'Choisis un pseudo de 2 à 20 caractères.');return{id:randomUUID(),token:randomBytes(32).toString('hex'),name,ready:false}};
const asset=(id)=>NODE_BY_ID[id]??STATIONS[id];
const active=(room)=>room.game.order.map(id=>room.players.find(p=>p.id===id)).filter(p=>p&&!room.game.bankrupt.includes(p.id));
const current=(room)=>room.players.find(p=>p.id===room.game.current);

function normalizeGame(g){g.houses??={};g.mortgages??={};g.tradeOffers??=[];g.auction??=null;g.remainingMoves??=0;g.extraTurn??=false;g.lastRoll??=null}
function netWorth(room,id){const g=room.game;normalizeGame(g);const assets=Object.entries(g.owners).filter(([,owner])=>owner===id).reduce((sum,[key])=>sum+(asset(key)?.price??200)*(g.mortgages[key]?0.5:1),0);const buildings=Object.entries(g.houses).filter(([key])=>g.owners[key]===id).reduce((sum,[key,count])=>sum+Math.floor((asset(key)?.price??200)/2)*count,0);return Math.round(g.money[id]+assets+buildings)}

export function createMetroRoom(name){const p=makePlayer(name);return{kind:'metropole',code:randomBytes(4).toString('hex').toUpperCase(),host:p.id,players:[p],messages:[],settings:{startingCash:1500,auction:true,doubleRent:true,evenBuild:true},game:null,updatedAt:Date.now()}}
export function joinMetroRoom(room,name){ensure(room.kind==='metropole','Ce code appartient à un autre jeu.');ensure(!room.game,'La partie a déjà commencé.');ensure(room.players.length<6,'Cette ville accueille six investisseurs maximum.');const p=makePlayer(name);ensure(!room.players.some(x=>x.name.toLowerCase()===p.name.toLowerCase()),'Ce pseudo est déjà utilisé.');room.players.push(p);return p}
export function authenticateMetro(room,token){const p=room.players.find(x=>x.token===token);ensure(p,'Session introuvable. Rejoins la ville à nouveau.');return p}

function finish(room,winner,reason){room.game.phase='finished';room.game.winner=winner;room.game.reason=reason;room.game.pending=null;return true}
function checkWinner(room){const g=room.game;const solvent=active(room);if(solvent.length===1)return finish(room,solvent[0].id,'Dernier investisseur solvable.');if(g.round>20){const winner=[...solvent].sort((a,b)=>netWorth(room,b.id)-netWorth(room,a.id))[0];return finish(room,winner.id,'Fin de la vingtième journée : patrimoine le plus élevé.')}return false}
function beginTurn(room){const g=room.game;normalizeGame(g);if(checkWinner(room))return;const p=current(room);g.rolled=null;g.remainingMoves=0;g.pending=null;g.phase=g.positions[p.id].station?'route':'roll'}
function endTurn(room){const g=room.game;normalizeGame(g);if(g.extraTurn&&!g.bankrupt.includes(g.current)){const event=g.lastEvent;g.extraTurn=false;beginTurn(room);g.lastEvent=`${event?`${event} `:''}Double : ${current(room).name} rejoue.`;return}const previous=g.order.indexOf(g.current);let next=previous;do next=(next+1)%g.order.length;while(g.bankrupt.includes(g.order[next])&&next!==previous);if(next<=previous)g.round++;g.turn=next;g.current=g.order[next];beginTurn(room)}
function charge(room,id,amount,creditor=null){const g=room.game;g.money[id]-=amount;if(creditor)g.money[creditor]+=amount;if(g.money[id]<0){g.phase='debt';g.pending={creditor};return false}return true}
function removeOffersFor(room,key){room.game.tradeOffers=room.game.tradeOffers.filter(o=>o.offerNode!==key&&o.wantNode!==key)}

function resolveOwnable(room,p,item){const g=room.game;const owner=g.owners[item.id];const price=item.price??220;const baseRent=item.rent??55;if(!owner){g.phase='purchase';g.pending={node:item.id,price};return}if(owner!==p.id&&!g.bankrupt.includes(owner)){if(g.mortgages[item.id]){g.lastEvent=`${item.name} est hypothéqué : aucun loyer.`;return endTurn(room)}const houses=g.houses[item.id]??0;const groupAssets=item.group?Object.values(NODE_BY_ID).filter(n=>n.group===item.group):[];const monopoly=item.group&&groupAssets.length>0&&groupAssets.every(n=>g.owners[n.id]===owner);const due=Math.round(baseRent*(houses?1+houses:monopoly&&room.settings?.doubleRent!==false?2:1));g.lastEvent=`Loyer versé à ${room.players.find(x=>x.id===owner)?.name} : ${due} M.`;if(!charge(room,p.id,due,owner))return}else g.lastEvent=`${item.name} appartient déjà à ${p.name}.`;endTurn(room)}
function resolveLanding(room,p,node){const g=room.game;if(!node)return endTurn(room);g.lastLanding=node.id;if(node.type==='property'||node.type==='company')return resolveOwnable(room,p,node);if(node.type==='salary'){g.money[p.id]+=200;g.lastEvent='Prime urbaine : +200 M.'}else if(node.type==='event'){const card=EVENT_CARDS[randomInt(EVENT_CARDS.length)];g.lastEvent=card.text;if(card.amount>=0)g.money[p.id]+=card.amount;else if(!charge(room,p.id,-card.amount))return}else if(node.type==='bank'){const amount=randomInt(2)===0?120:-100;g.lastEvent=amount>0?'Dividendes bancaires : +120 M.':'Frais bancaires : −100 M.';if(amount>0)g.money[p.id]+=amount;else if(!charge(room,p.id,-amount))return}endTurn(room)}
function resolveStation(room,p,id){room.game.lastLanding=id;resolveOwnable(room,p,STATIONS[id])}

function advance(room,p,steps){const g=room.game;const pos=g.positions[p.id];ensure(pos.route&&ROUTES[pos.route],'Choisis d’abord un itinéraire.');const route=ROUTES[pos.route];const distance=route.nodes.length-pos.index;if(steps>=distance){const remaining=steps-distance;g.positions[p.id]={station:route.to};g.remainingMoves=remaining;if(remaining>0){g.phase='route';g.lastEvent=`${STATIONS[route.to].name} traversée : choisissez la suite pour avancer encore de ${remaining} case${remaining>1?'s':''}.`;return}return resolveStation(room,p,route.to)}const nextIndex=pos.index+steps;g.remainingMoves=0;g.positions[p.id]={route:pos.route,index:nextIndex};resolveLanding(room,p,route.nodes[nextIndex])}

function proposeTrade(room,p,data){const g=room.game;const offerNode=clean(data.offerNode,24);const wantNode=clean(data.wantNode,24);const target=clean(data.to,40);ensure(g.owners[offerNode]===p.id,'Vous ne possédez pas le bien proposé.');ensure(g.owners[wantNode]===target&&target!==p.id,'Le bien demandé n’appartient pas à ce joueur.');ensure(!g.bankrupt.includes(target),'Ce joueur est en faillite.');g.tradeOffers.push({id:randomUUID(),from:p.id,to:target,offerNode,wantNode});g.lastEvent=`${p.name} propose un échange au Café des affaires.`}
function answerTrade(room,p,data,accept){const g=room.game;const offer=g.tradeOffers.find(o=>o.id===data.offerId);ensure(offer&&(offer.to===p.id||(!accept&&offer.from===p.id)),'Cette offre n’est plus disponible.');if(accept){ensure(g.owners[offer.offerNode]===offer.from&&g.owners[offer.wantNode]===offer.to,'Les propriétaires ont changé depuis cette offre.');g.owners[offer.offerNode]=offer.to;g.owners[offer.wantNode]=offer.from;g.lastEvent=`Échange conclu entre ${room.players.find(x=>x.id===offer.from)?.name} et ${p.name}.`}g.tradeOffers=g.tradeOffers.filter(o=>o.id!==offer.id)}
function finishAuction(room){const g=room.game;const auction=g.auction;if(auction.highestBidder){g.owners[auction.node]=auction.highestBidder;g.money[auction.highestBidder]-=auction.highestBid;g.lastEvent=`${room.players.find(x=>x.id===auction.highestBidder)?.name} remporte ${asset(auction.node).name} pour ${auction.highestBid} M.`}else g.lastEvent=`${asset(auction.node).name} reste à la banque.`;g.auction=null;endTurn(room)}
function auctionAction(room,p,action,data){const g=room.game;const auction=g.auction;ensure(g.phase==='auction'&&auction,'Aucune enchère en cours.');ensure(!g.bankrupt.includes(p.id)&&!auction.passed.includes(p.id),'Vous avez quitté cette enchère.');if(action==='bid'){const amount=Math.floor(Number(data.amount));ensure(Number.isFinite(amount)&&amount>=auction.highestBid+10,'La mise doit dépasser la meilleure offre de 10 M.');ensure(amount<=g.money[p.id],'Fonds insuffisants.');auction.highestBid=amount;auction.highestBidder=p.id}else{ensure(auction.highestBidder!==p.id,'Vous menez l’enchère : attendez les autres joueurs.');auction.passed.push(p.id)}const contenders=active(room).filter(x=>!auction.passed.includes(x.id));if((auction.highestBidder&&contenders.length===1&&contenders[0].id===auction.highestBidder)||(!auction.highestBidder&&contenders.length===0))finishAuction(room)}

export function metroAct(room,p,action,data={}){ensure(room.kind==='metropole','Ce salon appartient à un autre jeu.');const g=room.game;
  if(action==='chat'){const text=clean(data.text,400);ensure(text,'Le message est vide.');ensure(!p.lastMessage||Date.now()-p.lastMessage>=800,'Attends un instant avant de renvoyer un message.');p.lastMessage=Date.now();room.messages.push({id:randomUUID(),name:p.name,text});room.messages=room.messages.slice(-80)}
  else if(action==='leave'){ensure(!g||g.phase==='finished','La partie est en cours.');room.players=room.players.filter(x=>x.id!==p.id);if(room.host===p.id)room.host=room.players[0]?.id??'';if(g)room.game=null;room.players.forEach(x=>x.ready=false)}
  else if(action==='ready'){ensure(!g,'La partie a déjà commencé.');p.ready=!p.ready}
  else if(action==='configure'){ensure(!g&&p.id===room.host,'Seul l’hôte peut modifier les règles avant la partie.');const cash=Number(data.startingCash);ensure([1000,1500,2000,2500,3000].includes(cash),'Capital de départ invalide.');room.settings={startingCash:cash,auction:data.auction!==false,doubleRent:data.doubleRent!==false,evenBuild:data.evenBuild!==false}}
  else if(action==='start'){ensure(p.id===room.host,'Seul l’hôte peut lancer la partie.');ensure(!g,'La partie a déjà commencé.');ensure(room.players.length>=2&&room.players.every(x=>x.ready),'Il faut 2 à 6 joueurs, tous prêts.');const order=room.players.map(x=>x.id);for(let i=order.length-1;i>0;i--){const j=randomInt(i+1);[order[i],order[j]]=[order[j],order[i]]}const cash=room.settings?.startingCash??1500;room.game={phase:'roll',order,turn:0,round:1,current:order[0],money:Object.fromEntries(order.map(id=>[id,cash])),positions:Object.fromEntries(order.map(id=>[id,{route:'ouest-direct',index:2}])),owners:{},houses:{},mortgages:{},tradeOffers:[],auction:null,bankrupt:[],rolled:null,lastRoll:null,remainingMoves:0,extraTurn:false,pending:null,lastEvent:'Tous les investisseurs partent de la Prime régionale.',lastLanding:'f5',winner:null,reason:null}}
  else if(action==='reset'){ensure(p.id===room.host&&g?.phase==='finished','Seul l’hôte peut préparer une revanche.');room.game=null;room.players.forEach(x=>x.ready=false)}
  else{ensure(g&&g.phase!=='finished','Aucune partie en cours.');normalizeGame(g);ensure(data.revision===g.round*100+g.turn,'La partie a avancé.');if(action==='propose-trade')proposeTrade(room,p,data);else if(action==='accept-trade')answerTrade(room,p,data,true);else if(action==='reject-trade')answerTrade(room,p,data,false);else if(action==='bid'||action==='pass-auction')auctionAction(room,p,action,data);else{ensure(g.current===p.id,'Ce n’est pas votre tour.');
      if(action==='choose-route'){ensure(g.phase==='route','Aucune route à choisir.');const position=g.positions[p.id];ensure(position.station&&STATIONS[position.station].next.includes(data.route),'Cette route n’est pas disponible.');const remaining=g.remainingMoves;g.positions[p.id]={route:data.route,index:-1};if(remaining>0)advance(room,p,remaining);else g.phase='roll'}
      else if(action==='roll'){ensure(g.phase==='roll','Le dé a déjà été lancé.');const dice=[randomInt(1,7),randomInt(1,7)];const total=dice[0]+dice[1];const isDouble=dice[0]===dice[1];g.rolled=total;g.lastRoll={player:p.id,dice,total,isDouble};g.extraTurn=isDouble;advance(room,p,total)}
      else if(action==='buy'){ensure(g.phase==='purchase'&&g.pending?.node,'Aucun bien à acheter.');const item=asset(g.pending.node);ensure(item,'Bien introuvable.');ensure(!g.owners[item.id],'Ce bien a déjà un propriétaire.');ensure(g.money[p.id]>=g.pending.price,'Fonds insuffisants.');g.money[p.id]-=g.pending.price;g.owners[item.id]=p.id;g.lastEvent=`${item.name} rejoint votre patrimoine.`;endTurn(room)}
      else if(action==='skip'){ensure(g.phase==='purchase','Aucun achat à refuser.');if(room.settings?.auction!==false){g.phase='auction';g.auction={node:g.pending.node,highestBid:0,highestBidder:null,passed:[]};g.pending=null;g.lastEvent=`${asset(g.auction.node).name} part aux enchères.`}else{g.lastEvent='Le bien reste disponible.';endTurn(room)}}
      else if(action==='build'){const item=NODE_BY_ID[data.node];ensure(item?.type==='property'&&g.owners[item.id]===p.id,'Vous ne pouvez pas construire ici.');ensure(['roll','route'].includes(g.phase),'Construisez avant de lancer les dés.');ensure(!g.mortgages[item.id],'Le bien est hypothéqué.');const group=Object.values(NODE_BY_ID).filter(n=>n.group===item.group);ensure(group.length>0&&group.every(n=>g.owners[n.id]===p.id),'Possédez tout le quartier avant de construire.');const count=g.houses[item.id]??0;if(room.settings?.evenBuild!==false){const minimum=Math.min(...group.map(n=>g.houses[n.id]??0));ensure(count===minimum,'Construisez équitablement dans tout le quartier.')}ensure(count<4,'Cette propriété possède déjà quatre maisons.');const cost=Math.floor((item.price??200)/2);ensure(g.money[p.id]>=cost,'Fonds insuffisants pour construire.');g.money[p.id]-=cost;g.houses[item.id]=count+1;g.lastEvent=`${p.name} construit une maison sur ${item.name}.`}
      else if(action==='mortgage'){const item=asset(data.node);ensure(item&&g.owners[data.node]===p.id&&!g.mortgages[data.node],'Ce bien ne peut pas être hypothéqué.');ensure(['roll','route'].includes(g.phase),'Hypothéquez avant de lancer les dés.');ensure(!(g.houses[data.node]>0),'Vendez les maisons avant d’hypothéquer.');g.mortgages[data.node]=true;g.money[p.id]+=Math.floor((item.price??200)/2);g.lastEvent=`${item.name} est hypothéqué.`}
      else if(action==='unmortgage'){const item=asset(data.node);ensure(item&&g.owners[data.node]===p.id&&g.mortgages[data.node],'Ce bien n’est pas hypothéqué.');ensure(['roll','route'].includes(g.phase),'Levez l’hypothèque avant de lancer les dés.');const cost=Math.ceil((item.price??200)*0.55);ensure(g.money[p.id]>=cost,'Fonds insuffisants.');g.money[p.id]-=cost;delete g.mortgages[data.node];g.lastEvent=`Hypothèque levée sur ${item.name}.`}
      else if(action==='sell'){ensure(g.phase==='debt','Vous n’avez pas de dette à régler.');ensure(g.owners[data.node]===p.id,'Ce bien ne vous appartient pas.');const item=asset(data.node);delete g.owners[data.node];const houses=g.houses[data.node]??0;delete g.houses[data.node];delete g.mortgages[data.node];removeOffersFor(room,data.node);g.money[p.id]+=Math.floor((item.price??220)/2)+houses*Math.floor((item.price??220)/4);g.lastEvent=`${item.name} vendu à la banque.`;if(g.money[p.id]>=0)endTurn(room)}
      else if(action==='bankrupt'){ensure(g.phase==='debt','Vous n’êtes pas en défaut de paiement.');g.bankrupt.push(p.id);for(const[key,owner]of Object.entries(g.owners))if(owner===p.id){delete g.owners[key];delete g.houses[key];delete g.mortgages[key];removeOffersFor(room,key)}g.money[p.id]=0;g.lastEvent=`${p.name} quitte la course.`;endTurn(room)}
      else throw new MetroError('Action inconnue.')}}room.updatedAt=Date.now()}

export function metroView(room,p){const g=room.game;const base={kind:room.kind,code:room.code,host:room.host,me:p.id,players:room.players.map(({id,name,ready})=>({id,name,ready})),messages:room.messages,settings:room.settings??{startingCash:1500,auction:true,doubleRent:true,evenBuild:true}};if(!g)return{...base,game:null};normalizeGame(g);return{...base,game:{phase:g.phase,order:g.order,round:g.round,current:g.current,money:g.money,positions:g.positions,owners:g.owners,houses:g.houses,mortgages:g.mortgages,tradeOffers:g.tradeOffers,auction:g.auction,bankrupt:g.bankrupt,rolled:g.rolled,lastRoll:g.lastRoll,remainingMoves:g.remainingMoves,pending:g.pending,lastEvent:g.lastEvent,lastLanding:g.lastLanding,winner:g.winner,reason:g.reason,revision:g.round*100+g.turn,worth:Object.fromEntries(g.order.map(id=>[id,netWorth(room,id)]))}}}
