import { randomInt } from 'node:crypto';
const profiles={l1:['HOR','Industrie',38,1],r10:['MOB','Technologie',60,2],h15:['EAU','Réseaux',32,1],f6:['COO','Commerce',25,1],b6:['MAN','Industrie',35,1],n10:['EST','Énergie',45,1],'classic-12':['ELE','Énergie',40,1],'classic-28':['EAU','Réseaux',32,1]};
const clamp=value=>Math.max(5,Math.min(500,Math.round(value)));
export function createMarket(nodes,day=1){return{revision:0,day,news:[{day,text:'Ouverture de la Bourse : 100 actions disponibles par entreprise.'}],stocks:Object.fromEntries(nodes.filter(n=>n.type==='company').map(n=>{const [symbol,sector,price,dividend]=profiles[n.id]??['ENT','Industrie',40,1];return[n.id,{id:n.id,name:n.name,symbol,sector,price,previous:price,opening:price,dividend,supply:100,available:100,history:[price],reason:'Introduction en Bourse',holdings:{},costBasis:{},realized:{}}];}))};}
function news(m,text){m.news.push({day:m.day,text});m.news=m.news.slice(-8);}
export function moveQuote(m,stock,percent,reason){stock.previous=stock.price;stock.price=clamp(stock.price*(1+percent/100));stock.history.push(stock.price);stock.history=stock.history.slice(-24);stock.reason=reason;m.revision++;}
export function marketShock(m,percent,reason,sectors=null){if(!m)return;for(const s of Object.values(m.stocks))if(!sectors||sectors.includes(s.sector))moveQuote(m,s,percent,reason);news(m,reason+' ('+(percent>=0?'+':'')+percent+' %).');}
export function settleMarketDay(m,money,bankrupt,day,rng=randomInt){m.day=day;const trend=rng(-3,4);for(const s of Object.values(m.stocks)){s.opening=s.price;moveQuote(m,s,trend+rng(-8,9),'Séance quotidienne : tendance générale et résultats de l’entreprise');for(const [id,quantity]of Object.entries(s.holdings))if(!bankrupt.includes(id))money[id]+=quantity*s.dividend;}news(m,'Nouvelle séance : cours actualisés et dividendes versés aux actionnaires.');}
export function portfolioValue(m,id){return m?Object.values(m.stocks).reduce((sum,s)=>sum+(s.holdings[id]??0)*s.price,0):0;}
export function stockTransaction(m,id,node,quantity,sell,money){const s=m.stocks[node];const gross=s.price*quantity,fee=Math.max(1,Math.ceil(gross*.02));if(sell){const count=s.holdings[id]??0,allocated=(s.costBasis[id]??0)*quantity/count;s.holdings[id]=count-quantity;s.costBasis[id]=Math.max(0,(s.costBasis[id]??0)-allocated);s.realized[id]=(s.realized[id]??0)+gross-fee-allocated;s.available+=quantity;money[id]+=gross-fee;}else{s.holdings[id]=(s.holdings[id]??0)+quantity;s.costBasis[id]=(s.costBasis[id]??0)+gross+fee;s.available-=quantity;money[id]-=gross+fee;}moveQuote(m,s,(sell?-1:1)*Math.min(2,Math.max(1,Math.ceil(quantity/10))),sell?'Pression vendeuse des investisseurs':'Demande des investisseurs');return{gross,fee};}
export function releasePortfolio(m,id){if(!m)return;for(const s of Object.values(m.stocks)){s.available+=s.holdings[id]??0;delete s.holdings[id];delete s.costBasis[id];}}
