import { randomBytes, randomInt, randomUUID } from 'node:crypto';
import { EVENT_CARDS, NODE_BY_ID, ROUTES, STATIONS } from '../lib/metro-board.mjs';

export class MetroError extends Error {}
const ensure=(condition,message)=>{if(!condition)throw new MetroError(message)};
const clean=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
const makePlayer=(name)=>{name=clean(name,20);ensure(name.length>=2,'Choisis un pseudo de 2 à 20 caractères.');return{id:randomUUID(),token:randomBytes(32).toString('hex'),name,ready:false}};
export function createMetroRoom(name){const p=makePlayer(name);return{kind:'metropole',code:randomBytes(4).toString('hex').toUpperCase(),host:p.id,players:[p],messages:[],game:null,updatedAt:Date.now()}}
export function joinMetroRoom(room,name){ensure(room.kind==='metropole','Ce code appartient à un autre jeu.');ensure(!room.game,'La partie a déjà commencé.');ensure(room.players.length<6,'Cette ville accueille six investisseurs maximum.');const p=makePlayer(name);ensure(!room.players.some(x=>x.name.toLowerCase()===p.name.toLowerCase()),'Ce pseudo est déjà utilisé.');room.players.push(p);return p}
export function authenticateMetro(room,token){const p=room.players.find(x=>x.token===token);ensure(p,'Session introuvable. Rejoins la ville à nouveau.');return p}
const active=(room)=>room.game.order.map(id=>room.players.find(p=>p.id===id)).filter(p=>p&&!room.game.bankrupt.includes(p.id));
const current=(room)=>active(room)[room.game.turn%active(room).length];
const netWorth=(room,id)=>room.game.money[id]+Object.entries(room.game.owners).filter(([,owner])=>owner===id).reduce((sum,[node])=>sum+(NODE_BY_ID[node]?.price||200),0);
function checkWinner(room){const g=room.game;const solvent=active(room);if(solvent.length===1)return finish(room,solvent[0].id,'Dernier investisseur solvable.');if(g.round>20){const winner=[...solvent].sort((a,b)=>netWorth(room,b.id)-netWorth(room,a.id))[0];return finish(room,winner.id,'Fin de la vingtième journée : patrimoine le plus élevé.')}return false}
function finish(room,winner,reason){room.game.phase='finished';room.game.winner=winner;room.game.reason=reason;room.game.pending=null;return true}
function beginTurn(room){const g=room.game;if(checkWinner(room))return;const p=current(room);g.current=p.id;g.rolled=null;g.lastEvent=null;g.pending=null;g.phase=g.positions[p.id].station?'route':'roll'}
function endTurn(room){const g=room.game;const oldIndex=g.order.indexOf(g.current);let nextIndex=oldIndex;do{nextIndex=(nextIndex+1)%g.order.length}while(g.bankrupt.includes(g.order[nextIndex])&&nextIndex!==oldIndex);if(nextIndex<=oldIndex)g.round++;const nextId=g.order[nextIndex];g.turn=active(room).findIndex(x=>x.id===nextId);beginTurn(room)}
function charge(room,id,amount,creditor=null){const g=room.game;g.money[id]-=amount;if(creditor)g.money[creditor]+=amount;if(g.money[id]<0){g.phase='debt';g.pending={creditor};return false}return true}
function resolveLanding(room,p,node){const g=room.game;if(!node){endTurn(room);return}g.lastLanding=node.id;
  if(node.type==='property'||node.type==='company'){const owner=g.owners[node.id];const price=node.price??220;const rent=node.rent??55;if(!owner){g.phase='purchase';g.pending={node:node.id,price};return}if(owner!==p.id&&!g.bankrupt.includes(owner)){const group=node.group;const holdings=group?Object.values(NODE_BY_ID).filter(n=>n.group===group):[];const monopoly=group&&holdings.length>0&&holdings.every(n=>g.owners[n.id]===owner);const due=monopoly?rent*2:rent;g.lastEvent=`Loyer versé à ${room.players.find(x=>x.id===owner)?.name} : ${due} M.`;if(!charge(room,p.id,due,owner))return}}
  else if(node.type==='salary'){g.money[p.id]+=200;g.lastEvent='Prime urbaine : +200 M.'}
  else if(node.type==='event'){const card=EVENT_CARDS[randomInt(EVENT_CARDS.length)];g.lastEvent=card.text;if(card.amount>=0)g.money[p.id]+=card.amount;else if(!charge(room,p.id,-card.amount))return}
  else if(node.type==='bank'){const amount=randomInt(2)===0?120:-100;g.lastEvent=amount>0?'Dividendes bancaires : +120 M.':'Frais bancaires : −100 M.';if(amount>0)g.money[p.id]+=amount;else if(!charge(room,p.id,-amount))return}
  endTurn(room)}
export function metroAct(room,p,action,data={}){ensure(room.kind==='metropole','Ce salon appartient à un autre jeu.');const g=room.game;
  if(action==='chat'){const text=clean(data.text,400);ensure(text,'Le message est vide.');ensure(!p.lastMessage||Date.now()-p.lastMessage>=800,'Attends un instant avant de renvoyer un message.');p.lastMessage=Date.now();room.messages.push({id:randomUUID(),name:p.name,text});room.messages=room.messages.slice(-80)}
  else if(action==='leave'){ensure(!g||g.phase==='finished','La partie est en cours.');room.players=room.players.filter(x=>x.id!==p.id);if(room.host===p.id)room.host=room.players[0]?.id??'';if(g)room.game=null;room.players.forEach(x=>x.ready=false)}
  else if(action==='ready'){ensure(!g,'La partie a déjà commencé.');p.ready=!p.ready}
  else if(action==='start'){ensure(p.id===room.host,'Seul l’hôte peut lancer la partie.');ensure(!g,'La partie a déjà commencé.');ensure(room.players.length>=2&&room.players.every(x=>x.ready),'Il faut 2 à 6 joueurs, tous prêts.');const order=room.players.map(x=>x.id);for(let i=order.length-1;i>0;i--){const j=randomInt(i+1);[order[i],order[j]]=[order[j],order[i]]}room.game={phase:'route',order,turn:0,round:1,current:order[0],money:Object.fromEntries(order.map(id=>[id,1500])),positions:Object.fromEntries(order.map(id=>[id,{station:'central'}])),owners:{},bankrupt:[],rolled:null,pending:null,lastEvent:'La ville ouvre ses portes.',lastLanding:null,winner:null,reason:null}}
  else if(action==='reset'){ensure(p.id===room.host&&g?.phase==='finished','Seul l’hôte peut préparer une revanche.');room.game=null;room.players.forEach(x=>x.ready=false)}
  else{ensure(g&&g.phase!=='finished','Aucune partie en cours.');ensure(g.current===p.id,'Ce n’est pas votre tour.');ensure(data.revision===g.round*100+g.turn,'La partie a avancé.');
    if(action==='choose-route'){ensure(g.phase==='route','Aucune route à choisir.');const position=g.positions[p.id];ensure(position.station&&STATIONS[position.station].next.includes(data.route),'Cette route n’est pas disponible.');g.positions[p.id]={route:data.route,index:-1};g.phase='roll'}
    else if(action==='roll'){ensure(g.phase==='roll','Le dé a déjà été lancé.');const value=randomInt(1,7);g.rolled=value;const pos=g.positions[p.id];ensure(pos.route,'Choisis d’abord un itinéraire.');const route=ROUTES[pos.route];const nextIndex=pos.index+value;if(nextIndex>=route.nodes.length){g.positions[p.id]={station:route.to};g.lastEvent=`Arrivée à ${STATIONS[route.to].name}.`;endTurn(room)}else{g.positions[p.id]={route:pos.route,index:nextIndex};resolveLanding(room,p,route.nodes[nextIndex])}}
    else if(action==='buy'){ensure(g.phase==='purchase'&&g.pending?.node,'Aucun bien à acheter.');const node=NODE_BY_ID[g.pending.node];ensure(!g.owners[node.id],'Ce bien a déjà un propriétaire.');ensure(g.money[p.id]>=g.pending.price,'Fonds insuffisants.');g.money[p.id]-=g.pending.price;g.owners[node.id]=p.id;g.lastEvent=`${node.name} rejoint votre patrimoine.`;endTurn(room)}
    else if(action==='skip'){ensure(g.phase==='purchase','Aucun achat à refuser.');g.lastEvent='Le bien reste disponible.';endTurn(room)}
    else if(action==='sell'){ensure(g.phase==='debt','Vous n’avez pas de dette à régler.');ensure(g.owners[data.node]===p.id,'Ce bien ne vous appartient pas.');const node=NODE_BY_ID[data.node];delete g.owners[data.node];g.money[p.id]+=Math.floor((node.price??220)/2);g.lastEvent=`${node.name} vendu à la banque.`;if(g.money[p.id]>=0)endTurn(room)}
    else if(action==='bankrupt'){ensure(g.phase==='debt','Vous n’êtes pas en défaut de paiement.');g.bankrupt.push(p.id);for(const [node,owner]of Object.entries(g.owners))if(owner===p.id)delete g.owners[node];g.money[p.id]=0;g.lastEvent=`${p.name} quitte la course.`;endTurn(room)}
    else throw new MetroError('Action inconnue.')}
  room.updatedAt=Date.now()}
export function metroView(room,p){const g=room.game;const base={kind:room.kind,code:room.code,host:room.host,me:p.id,players:room.players.map(({id,name,ready})=>({id,name,ready})),messages:room.messages};if(!g)return{...base,game:null};return{...base,game:{phase:g.phase,order:g.order,round:g.round,current:g.current,money:g.money,positions:g.positions,owners:g.owners,bankrupt:g.bankrupt,rolled:g.rolled,pending:g.pending,lastEvent:g.lastEvent,lastLanding:g.lastLanding,winner:g.winner,reason:g.reason,revision:g.round*100+g.turn,worth:Object.fromEntries(g.order.map(id=>[id,netWorth(room,id)]))}}}
