import { randomBytes, randomInt, randomUUID } from 'node:crypto';

export class TraitorError extends Error {}
const ensure=(ok,message)=>{if(!ok)throw new TraitorError(message)};
const clean=(value,max)=>typeof value==='string'?value.trim().slice(0,max):'';
const shuffle=(items)=>{for(let i=items.length-1;i>0;i--){const j=randomInt(i+1);[items[i],items[j]]=[items[j],items[i]]}return items};
const makePlayer=(name)=>{name=clean(name,20);ensure(name.length>=2,'Choisis un pseudo de 2 à 20 caractères.');return{id:randomUUID(),token:randomBytes(32).toString('hex'),name,ready:false}};
const RULES={3:{mutins:1,planks:12,target:5},4:{mutins:1,planks:14,target:8},5:{mutins:1,planks:16,target:11},6:{mutins:2,planks:18,target:6},7:{mutins:2,planks:20,target:9},8:{mutins:2,planks:22,target:12}};
const ACTION_LABELS={plank:'Planche',spyglass:'Longue-vue',emptyPockets:'Vide tes poches',goodRiddance:'Bon débarras',miraculousCatch:'Pêche miraculeuse'};
const card=(type,value=null)=>({id:randomUUID(),type,value});
const makeDeck=(planks)=>shuffle([...Array.from({length:20},()=>card('loot',1)),...Array.from({length:12},()=>card('loot',-2)),...Array.from({length:10},()=>card('loot',0)),...Array.from({length:planks},()=>card('plank')),...Array.from({length:3},()=>card('spyglass')),...Array.from({length:3},()=>card('emptyPockets')),...Array.from({length:3},()=>card('goodRiddance')),...Array.from({length:3},()=>card('miraculousCatch'))]);

export function createTraitorRoom(name){const p=makePlayer(name);return{kind:'traitor-aboard',code:randomBytes(4).toString('hex').toUpperCase(),host:p.id,firstPlayer:p.id,players:[p],messages:[],game:null,updatedAt:Date.now()}}
export function joinTraitorRoom(room,name){ensure(room.kind==='traitor-aboard','Ce code appartient à un autre jeu.');ensure(!room.game,'La partie a déjà commencé.');ensure(room.players.length<8,'Le navire est complet.');const p=makePlayer(name);ensure(!room.players.some(x=>x.name.toLowerCase()===p.name.toLowerCase()),'Ce pseudo est déjà utilisé.');room.players.push(p);return p}
export function authenticateTraitor(room,token){const p=room.players.find(x=>x.token===token);ensure(p,'Session introuvable. Rejoins le navire à nouveau.');return p}
const active=(room)=>room.players.filter(p=>!room.game.eliminated.includes(p.id));
const current=(room)=>room.players[room.game.turnIndex];
const draw=(g,id,count)=>{const cards=[];for(let i=0;i<count&&g.drawPile.length;i++)cards.push(g.drawPile.pop());g.hands[id].push(...cards);return cards};
const revealRoles=(room)=>Object.fromEntries(room.players.map(p=>[p.id,room.game.roles[p.id]]));
function finish(room,winner,reason){room.game.phase='finished';room.game.winner=winner;room.game.reason=reason;room.game.revealedRoles=revealRoles(room);room.game.revealedChest=room.game.chest.map(c=>c.value)}
function checkTeams(room){const g=room.game,aboard=active(room),mutins=aboard.filter(p=>g.roles[p.id]==='mutin'),pirates=aboard.filter(p=>g.roles[p.id]==='pirate');if(mutins.length===0){finish(room,'pirates','Tous les Mutins ont été poussés à l’eau.');return true}if(mutins.length>=pirates.length){finish(room,'mutins','Les Mutins ne sont plus en infériorité numérique.');return true}return false}
function advance(room,{drawOne=true}={}){const g=room.game;if(g.phase==='finished')return;if(drawOne)draw(g,current(room).id,1);if(g.drawPile.length===0){finish(room,'mutins','Il n’y a plus de cartes dans la Pioche.');return}let next=g.turnIndex;do next=(next+1)%room.players.length;while(g.eliminated.includes(room.players[next].id));g.turnIndex=next;g.turn++;g.phase='playing';g.pending=null}
function removeCard(g,id,cardId){const hand=g.hands[id],index=hand.findIndex(c=>c.id===cardId);ensure(index>=0,'Cette carte n’est plus dans votre main.');return hand.splice(index,1)[0]}
function eliminate(room,target){const g=room.game;g.eliminated.push(target);g.discard.push(...g.hands[target],...Array.from({length:g.planks[target]},()=>card('plank')));g.hands[target]=[];g.planks[target]=0;g.log.push(`${room.players.find(p=>p.id===target)?.name} passe par-dessus bord et révèle son identité.`);return checkTeams(room)}

export function traitorAct(room,p,action,data={}){const g=room.game;
  if(action==='chat'){const text=clean(data.text,400);ensure(text,'Le message est vide.');ensure(!p.lastMessage||Date.now()-p.lastMessage>=800,'Attends un instant avant de renvoyer un message.');p.lastMessage=Date.now();room.messages.push({id:randomUUID(),name:p.name,text});room.messages=room.messages.slice(-80)}
  else if(action==='leave'){ensure(!g||g.phase==='finished','La partie est en cours.');room.players=room.players.filter(x=>x.id!==p.id);if(room.host===p.id)room.host=room.players[0]?.id??'';if(room.firstPlayer===p.id)room.firstPlayer=room.players[0]?.id??'';if(g)room.game=null;room.players.forEach(x=>x.ready=false)}
  else if(action==='ready'){ensure(!g,'La partie a déjà commencé.');p.ready=!p.ready}
  else if(action==='firstPlayer'){ensure(!g&&p.id===room.host,'Seul l’hôte choisit le premier joueur.');ensure(room.players.some(x=>x.id===data.target),'Joueur inconnu.');room.firstPlayer=data.target}
  else if(action==='start'){ensure(p.id===room.host,'Seul l’hôte peut lancer la partie.');ensure(!g,'La partie a déjà commencé.');ensure(room.players.length>=3&&room.players.length<=8&&room.players.every(x=>x.ready),'Il faut 3 à 8 joueurs, tous prêts.');const rule=RULES[room.players.length],ids=shuffle(room.players.map(x=>x.id)),mutins=ids.slice(0,rule.mutins),deck=makeDeck(rule.planks),hands={};for(const x of room.players){hands[x.id]=[];for(let i=0;i<3;i++)hands[x.id].push(deck.pop())}room.game={phase:'playing',turn:1,turnIndex:room.players.findIndex(x=>x.id===room.firstPlayer),roles:Object.fromEntries(room.players.map(x=>[x.id,mutins.includes(x.id)?'mutin':'pirate'])),hands,drawPile:deck,chest:[],discard:[],planks:Object.fromEntries(ids.map(id=>[id,0])),eliminated:[],target:rule.target,winner:null,reason:null,pending:null,log:[],revealedRoles:null,revealedChest:null,revealedChestTotal:null}}
  else if(action==='reset'){ensure(p.id===room.host&&g?.phase==='finished','Seul l’hôte peut préparer une nouvelle partie.');room.game=null;room.players.forEach(x=>x.ready=false)}
  else{ensure(g&&g.phase!=='finished','Aucune partie en cours.');ensure(data.turn===g.turn,'Le tour a avancé.');ensure(!g.eliminated.includes(p.id),'Vous êtes déjà à l’eau.');ensure(current(room).id===p.id,'Ce n’est pas votre tour.');
    if(action==='claim'){ensure(g.phase==='playing','Terminez d’abord votre action.');ensure(g.roles[p.id]==='pirate','Seul un Pirate peut vérifier le Coffre.');const total=g.chest.reduce((sum,c)=>sum+c.value,0);finish(room,total>=g.target?'pirates':'mutins',total>=g.target?'Le Coffre atteint la valeur annoncée.':'Le Coffre n’atteint pas la valeur annoncée.');g.revealedChestTotal=total}
    else if(action==='playLoot'){ensure(g.phase==='playing','Terminez d’abord votre action.');const announced=Number(data.announced),candidate=g.hands[p.id].find(c=>c.id===data.cardId);ensure([-2,0,1].includes(announced),'Annonce invalide.');ensure(candidate?.type==='loot','Une carte Action ne peut pas être placée dans le Coffre.');const played=removeCard(g,p.id,data.cardId);g.chest.push(played);g.log.push(`${p.name} ajoute un Butin face cachée et annonce ${announced>0?'+':''}${announced}.`);advance(room)}
    else if(action==='playAction'){ensure(g.phase==='playing','Terminez d’abord votre action.');const candidate=g.hands[p.id].find(c=>c.id===data.cardId);ensure(candidate&&candidate.type!=='loot','Choisis une carte Action.');if(candidate.type==='plank'||candidate.type==='emptyPockets')ensure(data.target!==p.id&&active(room).some(x=>x.id===data.target),'Choisis un autre joueur à bord.');const played=removeCard(g,p.id,data.cardId);g.discard.push(played);g.log.push(`${p.name} joue ${ACTION_LABELS[played.type]}.`);
      if(played.type==='plank'){g.planks[data.target]++;if(g.planks[data.target]>=3&&eliminate(room,data.target)){}else advance(room)}
      else if(played.type==='emptyPockets'){g.discard.push(...g.hands[data.target]);g.hands[data.target]=[];draw(g,data.target,3);advance(room)}
      else if(played.type==='goodRiddance'){g.discard.push(...g.chest.splice(Math.max(0,g.chest.length-2)));advance(room)}
      else if(played.type==='spyglass'){const seen=shuffle(g.chest.splice(Math.max(0,g.chest.length-3)));if(!seen.length)advance(room);else{g.phase='reorder-chest';g.pending={actor:p.id,cards:seen}}}
      else if(played.type==='miraculousCatch'){draw(g,p.id,3);g.phase='return-draw';g.pending={actor:p.id}}
    }
    else if(action==='resolveOrder'){ensure(g.pending?.actor===p.id,'Cette décision ne vous appartient pas.');const order=Array.isArray(data.order)?data.order:[];if(g.phase==='reorder-chest'){ensure(order.length===g.pending.cards.length&&new Set(order).size===order.length&&order.every(id=>g.pending.cards.some(c=>c.id===id)),'Ordre invalide.');g.chest.push(...order.map(id=>g.pending.cards.find(c=>c.id===id)));advance(room)}else if(g.phase==='return-draw'){ensure(order.length===2&&new Set(order).size===2,'Choisis deux cartes différentes.');const returned=order.map(id=>removeCard(g,p.id,id));g.drawPile.push(...returned);advance(room,{drawOne:false})}else throw new TraitorError('Aucun choix à résoudre.')}
    else throw new TraitorError('Action inconnue.')}
  room.updatedAt=Date.now()}

const publicCard=(c)=>({id:c.id,type:c.type,label:c.type==='loot'?`${c.value>0?'+':''}${c.value}`:ACTION_LABELS[c.type],value:c.value});
export function traitorView(room,p){const g=room.game,base={kind:room.kind,code:room.code,host:room.host,firstPlayer:room.firstPlayer,me:p.id,players:room.players.map(({id,name,ready})=>({id,name,ready})),messages:room.messages};if(!g)return{...base,game:null};const finished=g.phase==='finished',pending=g.pending?.actor===p.id?{cards:g.pending.cards?.map(publicCard)??[]}:null;return{...base,game:{phase:g.phase,turn:g.turn,current:current(room)?.id,role:g.roles[p.id],hand:g.hands[p.id].map(publicCard),handCounts:Object.fromEntries(room.players.map(x=>[x.id,g.hands[x.id].length])),chestCount:g.chest.length,drawCount:g.drawPile.length,discardCount:g.discard.length,planks:g.planks,eliminated:g.eliminated,target:g.target,winner:g.winner,reason:g.reason,pending,log:g.log.slice(-20),revealedRoles:finished?g.revealedRoles:null,revealedChest:finished?g.revealedChest:null,revealedChestTotal:finished?g.revealedChestTotal:null}}}
